"""Typed, privacy-safe contracts for Friday's interaction control plane."""

# Import trace exports before the candidate contract. The latter reaches the
# retrieval/storage graph, whose cold-start router imports FailureStage from
# this package while it is still being initialized.
# isort: off
from friday.interaction_control_plane.turn_trace import (
    TURN_TRACE_SCHEMA,
    CapabilityClass,
    CapabilityStepTrace,
    CompletionDecision,
    ContinuationKind,
    CountAccounting,
    FailureReason,
    FailureStage,
    IntentClass,
    OutcomeStatus,
    PlaybookClass,
    PublicationStatus,
    TokenAccounting,
    TraceBudget,
    TraceIdentifierDomain,
    TurnTrace,
    TurnTraceError,
    WorkRelation,
    derive_trace_identifier,
)
from friday.interaction_control_plane.archive_candidate_selection import (
    ARCHIVE_CANDIDATE_ITEM_SCHEMA,
    ARCHIVE_CANDIDATE_MAX_COUNT,
    ARCHIVE_CANDIDATE_QUESTION_SCHEMA,
    ARCHIVE_CANDIDATE_REASK_VERDICT_KIND,
    ARCHIVE_CANDIDATE_SELECTION_ACTIVE_FRAME_SCHEMA,
    ARCHIVE_CANDIDATE_SET_SCHEMA,
    ARCHIVE_CANDIDATE_WORK_ITEM_SCHEMA,
    ArchiveCandidateItem,
    ArchiveCandidateOrdinalQuestion,
    ArchiveCandidateQuestionKind,
    ArchiveCandidateQuestionState,
    ArchiveCandidateSelectionActiveFrame,
    ArchiveCandidateSelectionError,
    ArchiveCandidateSelectionWorkItem,
    ArchiveCandidateSet,
    archive_candidate_reask_prompt,
    archive_candidate_selection_offer_suffix,
    parse_archive_candidate_ordinal,
)

# isort: on
from friday.interaction_control_plane.work_item_contract import (
    RECALL_CONVERSATION_ACTIVE_FRAME_SCHEMA,
    RECALL_CONVERSATION_WORK_ITEM_SCHEMA,
    WORK_ITEM_ACTIVE_FRAME_MAX_BYTES,
    WORK_ITEM_MAX_REVISION,
    WORK_ITEM_TTL_HOURS,
    RecallConversationActiveFrame,
    RecallConversationWorkItem,
    RecallMessageRole,
    WorkCompletionContract,
    WorkGoal,
    WorkItemContractError,
    WorkKind,
    WorkPlaybook,
    WorkSourceScope,
    WorkState,
    WorkTransition,
    canonical_work_item_instant,
)
from friday.interaction_control_plane.work_item_schema import (
    WORK_ITEM_SCHEMA,
    WORK_ITEM_SCHEMA_VERSION,
    validate_work_item_schema,
)

__all__ = [
    "ARCHIVE_CANDIDATE_ITEM_SCHEMA",
    "ARCHIVE_CANDIDATE_MAX_COUNT",
    "ARCHIVE_CANDIDATE_QUESTION_SCHEMA",
    "ARCHIVE_CANDIDATE_REASK_VERDICT_KIND",
    "ARCHIVE_CANDIDATE_SELECTION_ACTIVE_FRAME_SCHEMA",
    "ARCHIVE_CANDIDATE_SET_SCHEMA",
    "ARCHIVE_CANDIDATE_WORK_ITEM_SCHEMA",
    "RECALL_CONVERSATION_ACTIVE_FRAME_SCHEMA",
    "RECALL_CONVERSATION_WORK_ITEM_SCHEMA",
    "TURN_TRACE_SCHEMA",
    "WORK_ITEM_ACTIVE_FRAME_MAX_BYTES",
    "WORK_ITEM_MAX_REVISION",
    "WORK_ITEM_SCHEMA",
    "WORK_ITEM_SCHEMA_VERSION",
    "WORK_ITEM_TTL_HOURS",
    "CapabilityClass",
    "CapabilityStepTrace",
    "CompletionDecision",
    "ContinuationKind",
    "CountAccounting",
    "FailureReason",
    "FailureStage",
    "IntentClass",
    "OutcomeStatus",
    "PlaybookClass",
    "PublicationStatus",
    "ArchiveCandidateItem",
    "ArchiveCandidateOrdinalQuestion",
    "ArchiveCandidateQuestionKind",
    "ArchiveCandidateQuestionState",
    "ArchiveCandidateSelectionActiveFrame",
    "ArchiveCandidateSelectionError",
    "ArchiveCandidateSelectionWorkItem",
    "ArchiveCandidateSet",
    "archive_candidate_selection_offer_suffix",
    "archive_candidate_reask_prompt",
    "parse_archive_candidate_ordinal",
    "RecallConversationActiveFrame",
    "RecallConversationWorkItem",
    "RecallMessageRole",
    "TraceBudget",
    "TraceIdentifierDomain",
    "TokenAccounting",
    "TurnTrace",
    "TurnTraceError",
    "WorkRelation",
    "WorkCompletionContract",
    "WorkGoal",
    "WorkItemContractError",
    "WorkKind",
    "WorkPlaybook",
    "WorkSourceScope",
    "WorkState",
    "WorkTransition",
    "canonical_work_item_instant",
    "derive_trace_identifier",
    "validate_work_item_schema",
]
