"""Public import surface for the pure retrieval-foundation contracts."""

from friday.retrieval._contract_utils import RetrievalContractError
from friday.retrieval.catalog_contract import (
    CatalogIndexLane,
    CatalogIndexState,
    CatalogIndexStatus,
    CatalogIngestState,
    CatalogItem,
    CatalogReviewState,
    IndexIncompleteReason,
)
from friday.retrieval.coverage_contract import (
    AbsenceDecision,
    CoverageState,
    SearchCorpus,
    SearchCoverage,
    SearchExecutionBinding,
    SearchLane,
    aggregate_absence_decision,
)
from friday.retrieval.identity_contract import (
    AuthorityScope,
    CanonicalObjectKind,
    LifecycleRef,
    LifecycleState,
    RepresentationKind,
    ResolvedSource,
    RevalidationTarget,
    RevisionKind,
    SourceKind,
    SourceRef,
    SourceRepresentation,
    SourceRevision,
)
from friday.retrieval.passage_contract import (
    EmbeddingCompatibility,
    EmbeddingIdentity,
    MessageRole,
    MessageWindowLocator,
    PassageLocatorKind,
    PassageRef,
    TextSpanLocator,
)
from friday.retrieval.temporal_contract import (
    TemporalFact,
    TemporalOrigin,
    TemporalPrecision,
    TemporalRole,
    TemporalValueKind,
    temporal_facts_for_role,
)

__all__ = [
    "AbsenceDecision",
    "AuthorityScope",
    "CanonicalObjectKind",
    "CatalogIndexLane",
    "CatalogIndexState",
    "CatalogIndexStatus",
    "CatalogIngestState",
    "CatalogItem",
    "CatalogReviewState",
    "CoverageState",
    "EmbeddingCompatibility",
    "EmbeddingIdentity",
    "IndexIncompleteReason",
    "LifecycleRef",
    "LifecycleState",
    "MessageRole",
    "MessageWindowLocator",
    "PassageLocatorKind",
    "PassageRef",
    "RepresentationKind",
    "ResolvedSource",
    "RetrievalContractError",
    "RevalidationTarget",
    "RevisionKind",
    "SearchCoverage",
    "SearchCorpus",
    "SearchExecutionBinding",
    "SearchLane",
    "SourceKind",
    "SourceRef",
    "SourceRepresentation",
    "SourceRevision",
    "TemporalFact",
    "TemporalOrigin",
    "TemporalPrecision",
    "TemporalRole",
    "TemporalValueKind",
    "TextSpanLocator",
    "aggregate_absence_decision",
    "temporal_facts_for_role",
]
