"""Pinned, bounded Java 21 source-to-JAR compiler.

The adapter accepts exactly one owned UTF-8 ``.java`` file, invokes the fixed
Temurin ``javac`` launcher inside the networkless Engineer sandbox, validates
every produced class file, and packages those classes itself as a reproducible
stored JAR.  Neither the source nor any generated bytecode is ever executed.
"""

from __future__ import annotations

import hashlib
import io
import os
import re
import signal
import stat
import subprocess
import tempfile
import zipfile
from collections.abc import Mapping
from contextlib import suppress
from pathlib import Path
from typing import Any, Literal, TypedDict

from .decompiler import _JDK_FILES as _DECOMPILER_JDK_FILES
from .decompiler import (
    JDK_ROOT,
    JDK_TREE_SHA256,
    JDK_VERSION,
    MAX_JDK_TREE_BYTES,
    SANDBOX_JDK_ROOT,
    TOOLS_ROOT,
    _fixed_files_match,
    _tree_identity,
)

SCHEMA = "friday.engineer.compile.v1"
PROFILE = "java21_single_source_library_jar_v1"
TOOL_NAME = "temurin-javac"
JAVAC_SHA256 = "55859b80e7a9c4c4736be19ad3addeb35112ca6d17a30c4e0e116afc0a499bdb"
JAVA_RELEASE = 21
CLASS_MAJOR_VERSION = 65
MAX_SOURCE_BYTES = 1024 * 1024
MAX_CLASS_FILES = 256
MAX_CLASS_BYTES = 8 * 1024 * 1024
MAX_JAR_BYTES = 16 * 1024 * 1024
MAX_CLASS_TREE_ENTRIES = 512
MAX_CLASS_PATH_BYTES = 512
JAVAC_TIMEOUT_SECONDS = 40.0

_SAFE_SOURCE_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]{0,119}\.java\Z")
_SAFE_CLASS_COMPONENT = re.compile(r"[A-Za-z_$][A-Za-z0-9_$]*\Z")
_JDK_FILES = {**_DECOMPILER_JDK_FILES, "bin/javac": JAVAC_SHA256}
_TOOLCHAIN_FAILURES = frozenset(
    {
        "toolchain_missing",
        "toolchain_incomplete",
        "toolchain_untrusted",
    }
)
_PRESTART_FAILURES = _TOOLCHAIN_FAILURES | {
    "compiler_launch_failed",
    "input_encoding_invalid",
    "input_size_invalid",
    "invalid_filename",
    "workspace_not_clean",
}


class CompileReport(TypedDict, total=False):
    ok: bool
    status: Literal["completed", "unavailable", "failed"]
    error: str
    schema: str
    profile: str
    tool_name: str
    tool_version: str
    jdk_version: str
    source_sha256: str
    jar_sha256: str
    source_size_bytes: int
    class_files: int
    class_bytes: int
    jar_size_bytes: int
    java_release: int
    class_major_version: int
    archive: Literal["jar"]
    compression: Literal["stored"]
    signed: bool
    manifest: bool
    runtime_validation: Literal["not_performed"]
    sample_executed: bool
    network: Literal["none"]


def _failure(code: str) -> CompileReport:
    reason = str(code or "compiler_failed")
    status: Literal["unavailable", "failed"] = (
        "unavailable" if reason in _TOOLCHAIN_FAILURES else "failed"
    )
    return {
        "ok": False,
        "status": status,
        "error": reason,
        "schema": SCHEMA,
        "profile": PROFILE,
        "tool_name": TOOL_NAME,
        "tool_version": JDK_VERSION,
        "jdk_version": JDK_VERSION,
        "java_release": JAVA_RELEASE,
        "class_major_version": CLASS_MAJOR_VERSION,
        "archive": "jar",
        "compression": "stored",
        "signed": False,
        "manifest": False,
        "runtime_validation": "not_performed",
        "sample_executed": False,
        "network": "none",
    }


def validate_source_payload(data: object, filename: str) -> str | None:
    """Return a closed admission error for an in-memory source, if any."""

    source_name = str(filename or "")
    if Path(source_name).name != source_name or _SAFE_SOURCE_NAME.fullmatch(source_name) is None:
        return "invalid_filename"
    if not isinstance(data, bytes) or not data or len(data) > MAX_SOURCE_BYTES:
        return "input_size_invalid"
    try:
        data.decode("utf-8", errors="strict")
    except UnicodeDecodeError:
        return "input_encoding_invalid"
    return "input_encoding_invalid" if b"\x00" in data else None


def compiler_work_started(error: object) -> bool:
    """Project whether a closed compiler failure occurred after javac entry."""

    return str(error or "compiler_failed") not in _PRESTART_FAILURES


def verify_toolchain(jdk_root: Path) -> dict[str, Any]:
    """Verify the exact JDK tree and compiler launcher without PATH lookup."""

    jdk = Path(jdk_root)
    if not jdk.exists():
        return {"ok": False, "reason": "toolchain_missing"}
    if not jdk.is_dir():
        return {"ok": False, "reason": "toolchain_untrusted"}
    required = tuple(jdk / relative for relative in _JDK_FILES)
    if any(not path.exists() for path in required):
        return {"ok": False, "reason": "toolchain_incomplete"}
    if _tree_identity(jdk, maximum_bytes=MAX_JDK_TREE_BYTES) != JDK_TREE_SHA256:
        return {"ok": False, "reason": "toolchain_untrusted"}
    if not _fixed_files_match(jdk, _JDK_FILES):
        return {"ok": False, "reason": "toolchain_untrusted"}
    try:
        javac = (jdk / "bin/javac").stat()
    except OSError:
        return {"ok": False, "reason": "toolchain_untrusted"}
    if not stat.S_ISREG(javac.st_mode) or not javac.st_mode & stat.S_IXUSR:
        return {"ok": False, "reason": "toolchain_untrusted"}
    return {
        "ok": True,
        "identity": "pinned_full_tree",
        "tool_name": TOOL_NAME,
        "tool_version": JDK_VERSION,
        "jdk_version": JDK_VERSION,
    }


def host_toolchain_preflight() -> dict[str, Any]:
    """Admit only the fixed owner-local Temurin installation."""

    if JDK_ROOT != TOOLS_ROOT / "jdk-21.0.12.1+1":
        return {"ok": False, "reason": "toolchain_untrusted"}
    return verify_toolchain(JDK_ROOT)


def sandbox_toolchain_preflight() -> dict[str, Any]:
    """Repeat full identity verification after the read-only bind."""

    return verify_toolchain(SANDBOX_JDK_ROOT)


def _javac_argv(
    source_path: Path,
    classes_path: Path,
    empty_path: Path,
    temp_path: Path = Path("/work/java-tmp"),
    home_path: Path = Path("/work/java-home"),
) -> list[str]:
    """Return the complete code-owned compiler argv."""

    return [
        str(SANDBOX_JDK_ROOT / "bin/javac"),
        "-J-Xms32m",
        "-J-Xmx512m",
        "-J-Xss512k",
        "-J-XX:ActiveProcessorCount=2",
        "-J-XX:CompressedClassSpaceSize=64m",
        "-J-XX:ReservedCodeCacheSize=128m",
        "-J-XX:MaxMetaspaceSize=256m",
        "-J-XX:MaxDirectMemorySize=128m",
        "-J-XX:+DisableAttachMechanism",
        "-J-XX:+ExitOnOutOfMemoryError",
        f"-J-Djava.io.tmpdir={temp_path}",
        f"-J-Duser.home={home_path}",
        "--release",
        str(JAVA_RELEASE),
        "-encoding",
        "UTF-8",
        "-proc:none",
        "-implicit:none",
        "-g:none",
        "-classpath",
        str(empty_path),
        "-sourcepath",
        str(empty_path),
        "-d",
        str(classes_path),
        str(source_path),
    ]


def _javac_environment() -> dict[str, str]:
    return {
        "LANG": "C.UTF-8",
        "LC_ALL": "C.UTF-8",
        "TZ": "UTC",
        "SOURCE_DATE_EPOCH": "315532800",
    }


def _read_source(path: Path) -> tuple[bytes | None, str | None]:
    artifact = Path(path)
    try:
        before = artifact.lstat()
        if artifact.resolve(strict=True) != artifact or not stat.S_ISREG(before.st_mode):
            return None, "input_size_invalid"
    except OSError:
        return None, "input_size_invalid"
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(artifact, flags)
    except OSError:
        return None, "input_size_invalid"
    try:
        details = os.fstat(descriptor)
        identity = (details.st_dev, details.st_ino, details.st_mode, details.st_size)
        if identity != (before.st_dev, before.st_ino, before.st_mode, before.st_size):
            return None, "input_size_invalid"
        if details.st_size <= 0 or details.st_size > MAX_SOURCE_BYTES:
            return None, "input_size_invalid"
        payload = bytearray()
        while len(payload) <= MAX_SOURCE_BYTES:
            chunk = os.read(descriptor, min(64 * 1024, MAX_SOURCE_BYTES + 1 - len(payload)))
            if not chunk:
                break
            payload.extend(chunk)
        if len(payload) != details.st_size or len(payload) > MAX_SOURCE_BYTES:
            return None, "input_size_invalid"
        current = artifact.lstat()
        if (current.st_dev, current.st_ino, current.st_mode, current.st_size) != identity:
            return None, "input_size_invalid"
    except OSError:
        return None, "input_size_invalid"
    finally:
        os.close(descriptor)
    source = bytes(payload)
    try:
        source.decode("utf-8", errors="strict")
    except UnicodeDecodeError:
        return None, "input_encoding_invalid"
    if b"\x00" in source:
        return None, "input_encoding_invalid"
    return source, None


def _write_private(path: Path, payload: bytes) -> None:
    flags = os.O_CREAT | os.O_EXCL | os.O_WRONLY
    flags |= getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    descriptor = os.open(path, flags, 0o600)
    try:
        view = memoryview(payload)
        while view:
            written = os.write(descriptor, view)
            if written <= 0:  # pragma: no cover - regular file invariant
                raise OSError("short write")
            view = view[written:]
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _safe_class_relative(path: Path) -> bool:
    encoded = path.as_posix().encode("utf-8", errors="strict")
    if not encoded or len(encoded) > MAX_CLASS_PATH_BYTES or path.suffix != ".class":
        return False
    parts = path.parts
    if not parts or any(part in {"", ".", ".."} for part in parts):
        return False
    stems = (*parts[:-1], path.stem)
    return all(_SAFE_CLASS_COMPONENT.fullmatch(part) is not None for part in stems)


def _read_class_file(path: Path, expected: os.stat_result) -> bytes | None:
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError:
        return None
    try:
        details = os.fstat(descriptor)
        identity = (details.st_dev, details.st_ino, details.st_mode, details.st_size, details.st_nlink)
        expected_identity = (
            expected.st_dev,
            expected.st_ino,
            expected.st_mode,
            expected.st_size,
            expected.st_nlink,
        )
        if (
            identity != expected_identity
            or not stat.S_ISREG(details.st_mode)
            or details.st_size < 8
            or details.st_size > MAX_CLASS_BYTES
            or details.st_nlink != 1
        ):
            return None
        payload = bytearray()
        while len(payload) <= details.st_size:
            chunk = os.read(descriptor, min(64 * 1024, details.st_size + 1 - len(payload)))
            if not chunk:
                break
            payload.extend(chunk)
        if len(payload) != details.st_size:
            return None
        current = path.lstat()
        if (current.st_dev, current.st_ino, current.st_mode, current.st_size, current.st_nlink) != identity:
            return None
        return bytes(payload)
    except OSError:
        return None
    finally:
        os.close(descriptor)


def _class_inventory(root: Path) -> tuple[list[tuple[str, bytes]] | None, int]:
    pending = [Path(root)]
    entries = 0
    total = 0
    inventory: list[tuple[str, bytes]] = []
    while pending:
        directory = pending.pop()
        try:
            children = list(os.scandir(directory))
        except OSError:
            return None, 0
        for child in children:
            entries += 1
            if entries > MAX_CLASS_TREE_ENTRIES:
                return None, 0
            path = Path(child.path)
            try:
                details = child.stat(follow_symlinks=False)
                relative = path.relative_to(root)
            except (OSError, ValueError):
                return None, 0
            if stat.S_ISDIR(details.st_mode):
                pending.append(path)
                continue
            if not stat.S_ISREG(details.st_mode) or not _safe_class_relative(relative):
                return None, 0
            payload = _read_class_file(path, details)
            if (
                payload is None
                or payload[:4] != b"\xca\xfe\xba\xbe"
                or int.from_bytes(payload[4:6], "big") != 0
                or int.from_bytes(payload[6:8], "big") != CLASS_MAJOR_VERSION
            ):
                return None, 0
            total += len(payload)
            inventory.append((relative.as_posix(), payload))
            if len(inventory) > MAX_CLASS_FILES or total > MAX_CLASS_BYTES:
                return None, 0
    if not inventory:
        return None, 0
    inventory.sort(key=lambda item: item[0].encode("ascii"))
    return inventory, total


def _deterministic_jar(classes: list[tuple[str, bytes]]) -> bytes | None:
    stream = io.BytesIO()
    try:
        with zipfile.ZipFile(stream, mode="x", compression=zipfile.ZIP_STORED) as archive:
            for relative, payload in classes:
                entry = zipfile.ZipInfo(relative, date_time=(1980, 1, 1, 0, 0, 0))
                entry.compress_type = zipfile.ZIP_STORED
                entry.create_system = 3
                entry.external_attr = (stat.S_IFREG | 0o444) << 16
                entry.flag_bits = 0
                archive.writestr(entry, payload)
                if stream.tell() > MAX_JAR_BYTES:
                    return None
    except (OSError, ValueError, zipfile.BadZipFile):
        return None
    payload = stream.getvalue()
    return payload if 0 < len(payload) <= MAX_JAR_BYTES else None


def compile_artifact(
    input_path: Path,
    filename: str,
    host_toolchain: object,
) -> tuple[bytes | None, CompileReport]:
    """Compile one validated source into a deterministic, never-executed JAR."""

    source_name = str(filename or "")
    source, source_error = _read_source(Path(input_path))
    if source is None:
        return None, _failure(source_error or "input_size_invalid")
    admission_error = validate_source_payload(source, source_name)
    if admission_error is not None:
        return None, _failure(admission_error)

    if not isinstance(host_toolchain, Mapping) or host_toolchain.get("ok") is not True:
        raw_reason = host_toolchain.get("reason") if isinstance(host_toolchain, Mapping) else None
        reason = str(raw_reason or "toolchain_untrusted")
        if reason not in _TOOLCHAIN_FAILURES:
            reason = "toolchain_untrusted"
        return None, _failure(reason)
    mounted = sandbox_toolchain_preflight()
    if mounted.get("ok") is not True:
        reason = str(mounted.get("reason") or "toolchain_untrusted")
        if reason not in _TOOLCHAIN_FAILURES:
            reason = "toolchain_untrusted"
        return None, _failure(reason)

    input_file = Path(input_path)
    try:
        with tempfile.TemporaryDirectory(prefix="friday-javac-", dir=input_file.parent) as directory:
            workspace = Path(directory)
            workspace.chmod(0o700)
            source_root = workspace / "java-src"
            classes_root = workspace / "java-classes"
            empty_root = workspace / "java-empty"
            temp_root = workspace / "java-tmp"
            home_root = workspace / "java-home"
            for path in (source_root, classes_root, empty_root, temp_root, home_root):
                path.mkdir(mode=0o700)
            source_path = source_root / source_name
            _write_private(source_path, source)
            argv = _javac_argv(source_path, classes_root, empty_root, temp_root, home_root)
            try:
                process = subprocess.Popen(  # noqa: S603 - exact pinned javac and fixed argv
                    argv,
                    stdin=subprocess.DEVNULL,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    cwd=workspace,
                    env=_javac_environment(),
                    shell=False,
                    close_fds=True,
                    start_new_session=True,
                )
            except OSError:
                return None, _failure("compiler_launch_failed")
            try:
                process.wait(timeout=JAVAC_TIMEOUT_SECONDS)
            except subprocess.TimeoutExpired:
                if process.poll() is None:
                    with suppress(ProcessLookupError):
                        os.killpg(process.pid, signal.SIGKILL)
                    process.wait()
                return None, _failure("compiler_timeout")
            if process.returncode != 0:
                return None, _failure("compiler_failed")
            classes, class_bytes = _class_inventory(classes_root)
            if classes is None:
                return None, _failure("compiler_output_invalid")
            jar = _deterministic_jar(classes)
            if jar is None:
                return None, _failure("compiler_output_exceeds_cap")
    except OSError:
        return None, _failure("workspace_not_clean")

    return jar, {
        "ok": True,
        "status": "completed",
        "schema": SCHEMA,
        "profile": PROFILE,
        "tool_name": TOOL_NAME,
        "tool_version": JDK_VERSION,
        "jdk_version": JDK_VERSION,
        "source_sha256": hashlib.sha256(source).hexdigest(),
        "jar_sha256": hashlib.sha256(jar).hexdigest(),
        "source_size_bytes": len(source),
        "class_files": len(classes),
        "class_bytes": class_bytes,
        "jar_size_bytes": len(jar),
        "java_release": JAVA_RELEASE,
        "class_major_version": CLASS_MAJOR_VERSION,
        "archive": "jar",
        "compression": "stored",
        "signed": False,
        "manifest": False,
        "runtime_validation": "not_performed",
        "sample_executed": False,
        "network": "none",
    }


__all__ = [
    "CLASS_MAJOR_VERSION",
    "JAVAC_SHA256",
    "JAVAC_TIMEOUT_SECONDS",
    "JDK_ROOT",
    "JDK_TREE_SHA256",
    "JDK_VERSION",
    "MAX_CLASS_BYTES",
    "MAX_CLASS_FILES",
    "MAX_JAR_BYTES",
    "MAX_SOURCE_BYTES",
    "PROFILE",
    "SANDBOX_JDK_ROOT",
    "SCHEMA",
    "TOOL_NAME",
    "compile_artifact",
    "compiler_work_started",
    "host_toolchain_preflight",
    "sandbox_toolchain_preflight",
    "validate_source_payload",
    "verify_toolchain",
]
