"""Command-line operations for Friday."""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import pathlib
import secrets
import sys
import tempfile
from contextlib import suppress
from pathlib import Path
from typing import Any

from friday import __version__
from friday.config import env as config_env


def configure_logging(level: str = "INFO") -> None:
    from friday.telemetry.logging import configure_secure_logging, secrets_from_environment

    configure_secure_logging(level, secrets_from_environment())


def _settings():
    from friday.config import load_settings

    return load_settings()


def _json_print(value: Any) -> None:
    print(json.dumps(value, ensure_ascii=False, indent=2, default=str))


_TTL_UNITS = {"s": 1, "m": 60, "h": 3600, "d": 86400}


def _parse_ttl_seconds(value: str) -> int:
    """Parse a TTL like '90d', '24h', '30m', '3600s', or bare seconds into seconds."""

    from friday.storage import MAX_API_TOKEN_TTL_SECONDS

    text = value.strip().lower()
    if not text:
        raise ValueError("empty TTL")
    unit = 1
    if text[-1] in _TTL_UNITS:
        unit = _TTL_UNITS[text[-1]]
        text = text[:-1]
    # Strict ASCII digits only: reject signs, spaces, underscores, unicode digits.
    if not (text.isascii() and text.isdigit()):
        raise ValueError(f"invalid TTL: {value!r}")
    seconds = int(text) * unit
    if seconds <= 0 or seconds > MAX_API_TOKEN_TTL_SECONDS:
        raise ValueError(f"TTL out of range: {value!r}")
    return seconds


def _write_private_text_atomic(path: Path, content: str) -> None:
    """Replace a local secret file atomically without following a target symlink."""

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        raise ValueError(f"Refusing to write configuration through a symlink: {path}")
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=path.parent,
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        with suppress(OSError):
            temporary.chmod(0o600)
        os.replace(temporary, path)
        with suppress(OSError):
            path.chmod(0o600)
    finally:
        temporary.unlink(missing_ok=True)


def _init_environment(args: argparse.Namespace) -> int:
    if args.home:
        os.environ["FRIDAY_HOME"] = str(Path(args.home).expanduser().resolve())
    from friday.config import ensure_runtime_dirs, load_settings

    settings = load_settings()
    ensure_runtime_dirs(settings)
    target = Path(args.env_file or Path.cwd() / ".env.local").expanduser()
    if not target.is_absolute():
        target = Path.cwd() / target
    target = target.absolute()
    if target.is_symlink():
        print(f"Отказываюсь писать конфигурацию через symlink: {target}", file=sys.stderr)
        return 2
    if target.exists() and not args.force:
        print(f"Не перезаписываю существующий файл: {target}")
        print("Используйте --force только если осознанно хотите заменить локальные секреты.")
        return 2
    api_token = secrets.token_urlsafe(48)
    bridge_secret = secrets.token_urlsafe(48)
    content = f"""# Generated by `jericho init`. Keep this file private.
FRIDAY_HOME={settings.home}
FRIDAY_PROFILE=qwen36-vl
FRIDAY_MODEL_ROOT={settings.model_root}

# Point BASE_URL at a local or LAN OpenAI-compatible endpoint, e.g. a vLLM on a
# neighbouring machine: http://192.168.1.50:8001/v1 . If that endpoint requires a
# token (vLLM --api-key), set FRIDAY_LLM_API_KEY and it is sent as a Bearer token.
FRIDAY_LLM_BASE_URL=http://127.0.0.1:8001/v1
FRIDAY_LLM_MODEL=dispatcher
FRIDAY_LLM_ENABLED=1
FRIDAY_LLM_API_KEY=
FRIDAY_VERIFY_ANSWERS=1
# Semantic search: point at a SEPARATE local OpenAI-compatible /embeddings service
# (the chat vLLM above does not serve embeddings). Leave disabled to run on
# lexical+FTS+graph retrieval only. EMBEDDINGS_API_KEY defaults to LLM_API_KEY.
# Turning this on WITHOUT a model name below disables dense recall entirely;
# startup validation refuses that combination rather than reporting it as working.
FRIDAY_EMBEDDINGS_ENABLED=0
FRIDAY_EMBEDDINGS_BASE_URL=http://127.0.0.1:8002/v1
FRIDAY_EMBEDDINGS_API_KEY=
FRIDAY_EMBEDDINGS_MODEL=
# Latency guard: cap how many (newest) vectors dense recall scores per query on a
# large corpus (the cosine scan is pure Python). 0 = no cap. Truncation is shown
# in the retrieval explain-trace (strategy.embeddings_capped).
FRIDAY_EMBEDDINGS_DENSE_MAX_OBJECTS=5000
# Passage-level recall: a long object is ALSO embedded in overlapping chunks, so one
# relevant paragraph of a whole imported article is findable. The whole-object vector
# stays the floor, so this can only add recall. 0 = off (pre-0.41 behaviour).
# Visible in the explain-trace as strategy.embeddings_chunked.
FRIDAY_EMBEDDINGS_CHUNK_CHARS=1200
FRIDAY_EMBEDDINGS_CHUNK_OVERLAP_CHARS=200
# Chunking multiplies inputs per object; cap one embeddings HTTP request.
FRIDAY_EMBEDDINGS_MAX_INPUTS_PER_REQUEST=64
# Near-duplicate Knowledge Object detection (needs embeddings). Cosine >= this
# flags a likely duplicate as a review-gated conflict; resolve = deprecate one.
FRIDAY_DEDUP_THRESHOLD=0.95
FRIDAY_DEDUP_INTERVAL_SEC=21600
# Retrieval-quality eval over the gold set: recall@k measured periodically,
# regression vs the previous run logged. Curate cases in the admin Quality view.
FRIDAY_EVAL_ENABLED=1
FRIDAY_EVAL_INTERVAL_SEC=86400
FRIDAY_EVAL_K=10
# Local speech-to-text for voice notes. Needs the optional extra:
# pip install 'jericho[voice]'. Runs fully offline; transcripts are
# model-generated, so they wait in the Inbox (no KO) until you confirm.
# Leave disabled to keep audio as un-extractable media. Empty language = auto.
FRIDAY_WHISPER_ENABLED=0
FRIDAY_WHISPER_MODEL=small
FRIDAY_WHISPER_DEVICE=cpu
FRIDAY_WHISPER_COMPUTE_TYPE=int8
FRIDAY_WHISPER_LANGUAGE=
FRIDAY_WHISPER_MAX_AUDIO_SEC=900
# Retention window (days) before a soft-deleted object is eligible for `jericho purge`.
FRIDAY_PURGE_RETENTION_DAYS=30
# Offsite mirror for verified backups (external disk / synced folder).
# A same-disk backup is NOT a real backup. Empty = mirroring off.
FRIDAY_BACKUP_MIRROR_DIR=
# Encrypt mirror copies (AES-256 via system openssl). Generate the key with
# `jericho backup-keygen`; keep a copy of the key SEPARATE from the mirror.
FRIDAY_BACKUP_ENCRYPTION_KEY_FILE=
# Что попадает в Inbox, прежде чем стать каноническим знанием:
#   assessed        — решает классификатор (как было всегда)
#   unless_explicit — прямо продвигается только явное сохранение (/note, «запомни»),
#                     всё остальное, включая загруженные файлы, ждёт человека
#   always          — не продвигается ничто
FRIDAY_INGESTION_REVIEW_POLICY=assessed
# Max graph-traversal depth for relational queries (hard safety ceiling 4).
FRIDAY_GRAPH_MAX_DEPTH=2

FRIDAY_API_HOST=127.0.0.1
FRIDAY_API_PORT=8000
FRIDAY_API_TOKEN={api_token}
FRIDAY_API_REQUIRE_TOKEN_ON_LOOPBACK=1
# Failed authentication attempts allowed per client IP per minute before 429.
FRIDAY_API_AUTH_FAILURE_LIMIT_PER_MINUTE=10
FRIDAY_CORS_ORIGINS=http://127.0.0.1:8000,http://localhost:8000

FRIDAY_TELEGRAM_BRIDGE_SECRET={bridge_secret}
FRIDAY_TELEGRAM_BOT_TOKEN=
# Deny-by-default: the bot ignores every chat until one of these is set.
FRIDAY_TELEGRAM_ALLOWED_CHAT_IDS=
FRIDAY_TELEGRAM_OWNER_CHAT_IDS=
# In a GROUP chat a first-time sender gets a read-and-chat 'guest' account, not the
# full 'user' preset (which grants web access, uploads and background missions on
# this instance). A private chat is unaffected; set this to 1 to opt out.
FRIDAY_TELEGRAM_GROUP_MEMBERS_FULL_ACCESS=0
FRIDAY_TELEGRAM_SIGNATURE_MAX_AGE_SEC=90
# Off by default. When on, anyone who writes to the bot in a PRIVATE chat that is
# not on the allowlist above gets their own isolated account (preset 'newcomer':
# chat, own knowledge, files, web search — no missions, no code execution, no
# admin). Groups are unaffected and still need the explicit allowlist.
FRIDAY_TELEGRAM_OPEN_REGISTRATION=0

FRIDAY_WORKERS_ENABLED=1
# Reminders organ: proactive Telegram nudges for upcoming dated events.
FRIDAY_REMINDERS_ENABLED=1
FRIDAY_REMINDERS_LEAD_DAYS=1
FRIDAY_REMINDERS_POLL_INTERVAL_SEC=900
# Reflection organ: weekly self-review digest (optional model synthesis).
FRIDAY_REFLECTION_ENABLED=1
FRIDAY_REFLECTION_INTERVAL_SEC=86400
FRIDAY_REFLECTION_MIN_KNOWLEDGE=3
# Chronicle organ (temporal presence): "on this day" resurfacing push.
FRIDAY_CHRONICLE_ENABLED=1
FRIDAY_CHRONICLE_INTERVAL_SEC=86400
# Sentinel organ (self-monitoring): pushes health alerts (crashed workers,
# stale/missing backups, unreachable vLLM) to the owner via the outbound channel.
FRIDAY_SENTINEL_ENABLED=1
FRIDAY_SENTINEL_INTERVAL_SEC=3600
FRIDAY_SENTINEL_CHECK_LLM=1
# Inject the derived user model (people/projects/interests) into chat context.
FRIDAY_PROFILE_IN_CONTEXT=1
# Quiet hours (UTC) — no proactive organ enqueues messages in this window.
FRIDAY_QUIET_HOURS_START=22
FRIDAY_QUIET_HOURS_END=8
FRIDAY_WEB_ALLOW_PRIVATE_NETWORKS=0
FRIDAY_CODE_EXECUTION_ENABLED=0
FRIDAY_MAX_UPLOAD_BYTES=52428800
FRIDAY_MAX_ARCHIVE_ENTRIES=500
FRIDAY_MAX_ARCHIVE_UNCOMPRESSED_BYTES=262144000
"""
    _write_private_text_atomic(target, content)
    print(f"Friday инициализирован: {settings.home}")
    print(f"Конфигурация и новые секреты записаны в: {target}")
    print(f"Каталог модели: {settings.model_dir}")
    print("\nДальше:")
    print("  1. Положите веса модели в указанный каталог.")
    print("  2. Заполните FRIDAY_TELEGRAM_BOT_TOKEN в .env.local (Telegram можно подключить позже).")
    print("  3. Запустите vLLM и затем всё остальное одной командой: `jericho up`.")
    print("  4. Проверьте установку: `jericho status --check-llm`.")
    print("  5. Для автозапуска: `jericho install-services` (systemd --user юниты).")
    print("  6. После первых данных создайте копию: `jericho backup --label first`.")
    return 0


def _status(args: argparse.Namespace) -> int:
    from friday.config import load_settings
    from friday.diagnostics import collect_diagnostics

    settings = load_settings()
    result = collect_diagnostics(settings, check_llm_port=args.check_llm, check_secrets=True)
    if args.json:
        _json_print({"version": __version__, **result})
    else:
        db = result["database"]
        backups = result.get("backups", {})
        workers = result.get("workers", {})
        lease = result.get("backend_lease", {})
        print(f"Friday {__version__}")
        print(f"State: {result.get('state', 'unknown')}")
        print(f"Home: {settings.home}")
        print(f"Database: {settings.database_path}")
        print(f"Schema: {db.get('schema_version', 'not initialized')}")
        print(f"Database integrity: {db.get('integrity_check', 'not created')}")
        latest = backups.get("latest") or {}
        if backups.get("verified"):
            print(f"Latest backup: verified · {latest.get('database')} · {latest.get('created_at')}")
        else:
            print(f"Latest backup: {backups.get('state', 'unknown')}")
        backend_state = lease.get("state", "unknown")
        backend_pid = lease.get("pid")
        print(f"Backend lease: {backend_state}{f' · pid {backend_pid}' if backend_pid else ''}")
        from friday.diagnostics.runtime_lease import inspect_process_lease

        bridge_lease = inspect_process_lease(
            settings.state_dir / "telegram-inbox.sqlite3.lock",
            protocol="friday.telegram-bridge.v1",
        )
        bridge_pid = bridge_lease.get("pid")
        print(
            f"Bridge lease: {bridge_lease.get('state', 'unknown')}"
            f"{f' · pid {bridge_pid}' if bridge_pid else ''}"
        )
        bridge_queue = result.get("bridge_queue", {})
        if bridge_queue.get("state") == "present":
            print(
                "Bridge queue: "
                f"{bridge_queue.get('pending', 0)} pending · "
                f"{bridge_queue.get('dead_letter', 0)} dead-letter"
            )
        outbound_pending = db.get("outbound_pending")
        if outbound_pending is not None:
            print(f"Outbound queue: {outbound_pending} pending")
        print(
            "Workers: "
            f"{workers.get('state', 'unknown')} · "
            f"tasks {workers.get('task_count', 0)} · "
            f"healthy {'yes' if workers.get('healthy', True) else 'no'}"
        )
        print(
            f"Model directory: {settings.model_dir} "
            f"({'weights detected' if result['paths']['model'].get('usable_files_detected') else 'empty or missing'})"
        )
        print(f"Configuration: {'OK' if result['ok'] else 'needs attention'}")
        for issue in result.get("configuration_issues", []):
            print(f"  - {issue}")
        if args.check_llm:
            endpoint = result.get("llm_endpoint", {})
            print(f"LLM endpoint: {'reachable' if endpoint.get('reachable') else 'unreachable'}")
        actions = result.get("actions", [])
        if actions:
            print("\nRecommended actions:")
            for action in actions:
                marker = {"error": "!", "warning": "~", "setup": "+"}.get(
                    str(action.get("severity")),
                    "-",
                )
                print(f"  {marker} {action.get('title')}: {action.get('detail')}")
                if action.get("command"):
                    print(f"      {action['command']}")
    return 0 if result.get("state") in {"ready", "attention"} else 1


def _doctor(args: argparse.Namespace) -> int:
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.diagnostics import collect_diagnostics

    settings = load_settings()
    ensure_runtime_dirs(settings)
    result = collect_diagnostics(settings, check_llm_port=args.check_llm, check_secrets=True)
    _json_print(result)
    return 0 if result.get("state") in {"ready", "attention"} else 1


def _search_source(args: argparse.Namespace) -> int:
    """Search the SOURCE text of ingested material, respecting the Inbox verdict."""
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.permissions import LEGACY_OWNER_USER_ID
    from friday.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        user_id = args.user or LEGACY_OWNER_USER_ID
        items = storage.search_raw_objects(user_id, args.query, limit=args.limit)
        if args.json:
            _json_print({"query": args.query, "items": items, "count": len(items)})
            return 0
        if not items:
            print("Ничего не найдено в доступном исходном тексте.")
            # A source search finding nothing is not proof the phrase was never
            # ingested — only that it is not in material the reviewer kept.
            print("Отклонённый в Inbox материал сюда не входит: это вердикт, а не фильтр.")
            return 0
        for item in items:
            marker = "знание" if item.get("knowledge_object_id") else item.get("inbox_status") or "—"
            print(f"[{marker}] {item.get('source')}: {item.get('source_ref') or item.get('id')}")
            excerpt = str(item.get("excerpt") or "").replace("\n", " ")
            if excerpt:
                print(f"    …{excerpt}…")
        print(f"\nНайдено: {len(items)}")
        return 0
    finally:
        storage.close()


def _events(args: argparse.Namespace) -> int:
    """What happened while nobody was watching."""
    from friday.config import load_settings
    from friday.storage import init_storage

    settings = load_settings()
    storage = init_storage(settings)
    try:
        events = storage.list_events(event_type=args.type, limit=args.limit)
        total = storage.count_events()
    finally:
        storage.close()

    if args.json:
        _json_print(events)
        return 0
    if not events:
        print("Событий пока нет." if not args.type else f"Событий типа {args.type} нет.")
        return 0
    print(f"Последние {len(events)} из {total} записей:\n")
    for event in events:
        stamp = str(event.get("created_at") or "")[:19].replace("T", " ")
        payload = event.get("payload") or {}
        detail = ", ".join(f"{key}={value}" for key, value in payload.items() if value not in (None, ""))
        print(f"  {stamp}  {str(event.get('event_type')):20} {detail}")
    return 0


def _eval_bootstrap(args: argparse.Namespace) -> int:
    """Draft gold cases from existing knowledge; save only what the owner keeps."""
    from friday.agent_runtime.llm import LLMRouter
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.eval_bootstrap import propose_cases, save_accepted
    from friday.storage import init_storage

    settings = load_settings()
    if not settings.llm_enabled:
        print("Нужна работающая модель: FRIDAY_LLM_ENABLED=1.", file=sys.stderr)
        return 2
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        user_id = _resolve_import_user(storage, args.user)
        proposals = asyncio.run(propose_cases(storage, LLMRouter(settings), user_id, limit=args.limit))
        if not proposals:
            print("Не из чего строить: в базе нет знаний.")
            return 0
        accepted = [item for item in proposals if item.accepted]
        for item in proposals:
            if item.accepted:
                print(f"  + {item.query}\n      → {item.title[:70]}")
            else:
                shared = f" ({', '.join(item.shared_tokens)})" if item.shared_tokens else ""
                print(f"  − {item.query or '—'}\n      отклонён: {item.reason}{shared}")
        print(f"\nГодных {len(accepted)} из {len(proposals)}.")
        if not args.save:
            print("Ничего не сохранено. Повторите с --save, если вопросы разумны.")
            return 0
        saved = save_accepted(storage, user_id, accepted)
        print(f"Сохранено кейсов: {saved}. Проверить качество поиска: jericho doctor / раздел «Качество».")
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    finally:
        storage.close()
    return 0


def _model_check(args: argparse.Namespace) -> int:
    """Probe the configured endpoint by generating, not by connecting."""
    from friday.config import load_settings
    from friday.model_check import check_model

    settings = load_settings()
    if not settings.llm_enabled:
        print("FRIDAY_LLM_ENABLED=0 — проверяю эндпоинт всё равно, но Friday его не использует.\n")
    report = check_model(settings, timeout=args.timeout)
    if args.json:
        _json_print(report.to_dict())
        return 0 if report.ok else 1

    print(f"Эндпоинт: {report.base_url}\nМодель:   {report.model}\n")
    for probe in report.probes:
        mark = "✓" if probe.ok else "✗"
        timing = f"{probe.seconds:5.2f}s" if probe.seconds else "     "
        tokens = f" {probe.tokens} ток." if probe.tokens is not None else ""
        print(f"  {mark} {probe.name:22} {timing}{tokens}  {probe.detail}")
    print()
    print("Готово к работе." if report.ok else "Есть проблемы — см. отметки ✗ выше.")
    return 0 if report.ok else 1


def _backup(args: argparse.Namespace) -> int:
    from friday.backup_mirror import mirror_backups
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        result = storage.create_backup(label=args.label)
    finally:
        storage.close()
    mirror = mirror_backups(settings)
    _json_print({**result, "mirror": mirror})
    if not mirror.get("enabled"):
        print(
            "⚠ Зеркалирование выключено: копия лежит на том же диске. "
            "Настройте FRIDAY_BACKUP_MIRROR_DIR (внешний диск/синхронизируемый каталог).",
            file=sys.stderr,
        )
    return 0


def _backup_keygen(args: argparse.Namespace) -> int:
    """Generate a backup-encryption key file (referenced by the env setting)."""
    from friday.config import load_settings

    settings = load_settings()
    target = Path(args.out).expanduser() if args.out else settings.backup_encryption_key_file
    if target is None:
        print(
            "Укажите --out или задайте FRIDAY_BACKUP_ENCRYPTION_KEY_FILE в .env.local",
            file=sys.stderr,
        )
        return 2
    if target.exists() and not args.force:
        print(f"Не перезаписываю существующий ключ: {target} (используйте --force)")
        return 2
    _write_private_text_atomic(target, secrets.token_hex(32) + "\n")
    print(f"Ключ шифрования бэкапов записан: {target} (права 600)")
    print("Храните копию ключа ОТДЕЛЬНО от зеркала: без ключа .enc-копии невосстановимы.")
    return 0


def _decrypt_backup(args: argparse.Namespace) -> int:
    from friday.backup_mirror import decrypt_file
    from friday.config import load_settings

    settings = load_settings()
    key_file = Path(args.key).expanduser() if args.key else settings.backup_encryption_key_file
    if key_file is None:
        print("Укажите --key или задайте FRIDAY_BACKUP_ENCRYPTION_KEY_FILE", file=sys.stderr)
        return 2
    source = Path(args.filename).expanduser()
    destination = (
        Path(args.out).expanduser() if args.out else source.with_name(source.name.removesuffix(".enc"))
    )
    if destination.exists():
        print(f"Не перезаписываю существующий файл: {destination}", file=sys.stderr)
        return 2
    decrypt_file(source, destination, key_file)
    print(f"Расшифровано: {destination}")
    print("Дальше: `jericho verify-backup` рядом с манифестом или `jericho restore-backup`.")
    return 0


def _verify_backup(args: argparse.Namespace) -> int:
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        filename = args.filename
        if not filename:
            backups = storage.list_backups()
            if not backups:
                print("Резервных копий не найдено.", file=sys.stderr)
                return 2
            filename = str(backups[0]["database"])
        result = storage.verify_backup(filename)
    finally:
        storage.close()
    _json_print(result)
    return 0 if result.get("ok") else 1


def _restore_backup(args: argparse.Namespace) -> int:
    """Restore one database backup while the backend process role is exclusive."""

    if not args.yes:
        print(
            "Восстановление заменит активную SQLite-базу. Повторите команду с --yes после "
            "остановки backend и Telegram bridge.",
            file=sys.stderr,
        )
        return 2

    from friday.config import ensure_runtime_dirs, load_settings
    from friday.diagnostics.runtime_lease import ProcessLease
    from friday.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    with ProcessLease(settings.state_dir / "backend.lock", protocol="friday.backend.v1"):
        storage = init_storage(settings)
        try:
            filename = args.filename
            if not filename:
                backups = storage.list_backups()
                if not backups:
                    print("Резервных копий не найдено.", file=sys.stderr)
                    return 2
                filename = str(backups[0]["database"])
            result = storage.restore_backup(
                filename,
                safety_label=f"pre-restore-{Path(filename).stem}",
            )
        finally:
            storage.close()
    _json_print(result)
    print(
        "Важно: восстановлена только SQLite-база; raw files, memory vault, веса модели и "
        "локальная конфигурация не изменялись.",
        file=sys.stderr,
    )
    return 0


def _export_user(args: argparse.Namespace) -> int:
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        result = storage.export_user(args.user_id)
    finally:
        storage.close()
    _json_print(result)
    return 0


def _resolve_import_user(storage: Any, requested: str | None) -> str:
    """Pick the tenant to import into, refusing to guess when guessing could misfile.

    A single-account instance is the normal case and asking for --user every time is
    friction for nothing. With several accounts there is no defensible default: the
    files would land in someone's knowledge base, and the wrong one is not recoverable
    by a flag.
    """
    if requested:
        return requested
    users = storage.list_users(limit=5)
    if len(users) == 1:
        return str(users[0]["id"])
    if not users:
        raise ValueError("No accounts exist yet; pass --user to create one for the import")
    raise ValueError(f"{len(users)} accounts exist; pass --user to say which one these files belong to")


def _import(args: argparse.Namespace) -> int:
    """Walk a directory and put every file through the review gate."""
    from friday.bulk_import import Outcome, plan_import, run_import, summarise
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.ingestion import IngestionPipeline
    from friday.knowledge_graph import KnowledgeGraph
    from friday.storage import init_storage

    root = Path(args.path).expanduser()
    if not root.exists():
        print(f"Путь не найден: {root}", file=sys.stderr)
        return 2

    settings = load_settings()
    ensure_runtime_dirs(settings)
    plan = plan_import(
        root,
        max_bytes=settings.max_upload_bytes,
        suffixes=args.suffix,
        include_hidden=args.include_hidden,
        follow_symlinks=args.follow_symlinks,
        # План НЕ ограничивается числом партии: ограничение по плану даёт те же
        # первые N файлов на каждом запуске. Партию отмеряет `run_import` по
        # загруженным. Потолок плана оставлен щедрым, чтобы обход не был бесконечным
        # на дереве, где почти всё уже загружено.
        limit=(args.limit * 20 if args.limit else None),
    )

    megabytes = plan.total_bytes / (1024 * 1024)
    print(f"Найдено файлов: {len(plan.candidates)} ({megabytes:.1f} МиБ), пропущено: {len(plan.skipped)}")
    if plan.candidates:
        shown = list(plan.by_suffix().items())[:8]
        print("  По типам: " + ", ".join(f"{suffix} {count}" for suffix, count in shown))
    if plan.skipped:
        print("  Пропущено: " + ", ".join(f"{why} {count}" for why, count in plan.skip_reasons().items()))
    if args.dry_run:
        print("\n--dry-run: ничего не записано.")
        return 0
    if not plan.candidates:
        return 0

    storage = init_storage(settings)
    try:
        try:
            user_id = _resolve_import_user(storage, args.user)
        except ValueError as exc:
            print(str(exc), file=sys.stderr)
            return 2
        pipeline = IngestionPipeline(settings, storage, KnowledgeGraph(storage), None)
        print(f"Импорт в аккаунт {user_id}. Всё уходит в Inbox на ваше подтверждение.\n")

        def progress(index: int, total: int, outcome: Outcome) -> None:
            if outcome.status == "failed":
                print(f"  [{index}/{total}] ОШИБКА {outcome.path}: {outcome.detail}", file=sys.stderr)
            elif not args.quiet:
                mark = "=" if outcome.status == "duplicate" else "+"
                print(f"  [{index}/{total}] {mark} {outcome.path.name}")

        try:
            outcomes = asyncio.run(
                run_import(pipeline, user_id, plan, on_progress=progress, stop_after=args.limit)
            )
        except KeyboardInterrupt:
            # Content-hash idempotency means a re-run resumes; say so rather than
            # leaving the user guessing whether they have to start over.
            print("\nПрервано. Повторите ту же команду — уже загруженные файлы будут пропущены.")
            return 130
    finally:
        storage.close()

    counts = summarise(outcomes)
    print(
        f"\nГотово: загружено {counts['ingested']}, "
        f"уже было {counts['duplicate']}, ошибок {counts['failed']}."
    )
    if counts["ingested"]:
        print("Разобрать: /inbox в Telegram или раздел Inbox в админке.")
    return 1 if counts["failed"] else 0


def _reindex_embeddings(args: argparse.Namespace) -> int:
    """Заставить индексатор пересчитать вектора, не оставляя поиск без них.

    Понадобилось потому, что вектор, посчитанный по неверному тексту, в базе
    неотличим от honest: хэш пишется от полного текста. Когда такое обнаружено —
    заменой лечения на отказ по длине, сменой модели, правкой потолков — нужен
    способ сказать «пересчитай всё», и он не должен требовать ни остановки
    сервиса, ни ручного удаления строк.

    Работает пометкой, а не удалением: старый вектор продолжает отвечать на поиск,
    пока индексатор не заменит его. Поэтому команда безопасна на живой системе —
    худшее, что она делает, это работа для видеокарты.
    """

    if not args.yes:
        print(
            "Команда пометит вектора устаревшими, и фоновый индексатор пересчитает их заново. "
            "Поиск продолжит работать на прежних векторах до замены. Повторите с --yes.",
            file=sys.stderr,
        )
        return 2

    from friday.config import ensure_runtime_dirs, load_settings
    from friday.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        marked = storage.mark_embeddings_stale(user_id=args.user)
        storage.record_event(
            "embeddings.reindex_requested",
            {"marked": marked, "user_id": args.user or "*"},
        )
    finally:
        storage.close()
    scope = f"арендатора {args.user}" if args.user else "всех арендаторов"
    print(f"Помечено устаревшими векторов {scope}: {marked}.")
    print("Пересчёт идёт фоновым индексатором; следите за `jericho status` или журналом.")
    return 0


def _backfill_document_dates(args: argparse.Namespace) -> int:
    """Достать собственную дату документа у уже загруженных файлов.

    Дату из провенанса файла (docProps/core.xml, /CreationDate) начали снимать
    при приёме, а корпус загружен раньше: у владельца дата создания у 1531
    объекта из 1537 — это день импорта, то есть хронологии архива не было вовсе.
    Замер на его же файлах: 84% дают настоящую дату, разброс 2006-2026.

    Безопасно на живой системе: читает файлы, пишет ОДНО поле метаданных и не
    создаёт версий — это дозапись утраченного провенанса, а не правка знания.
    Идемпотентно: объект с датой второй раз не берётся, поэтому прерванный
    прогон продолжается повторным запуском.
    """
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.documents import _office_document_date, _pdf_document_date_from_bytes
    from friday.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    scanned = dated = missing = 0
    # Курсор, а не множество просмотренных. Объект, у которого даты в файле НЕТ,
    # остаётся «без даты» навсегда, поэтому выборка «первые N без даты» отдаёт его
    # снова и снова: прежний цикл отфильтровывал их по `seen`, получал пустую
    # пачку и ВЫХОДИЛ — считая концом корпуса то, что было концом первой страницы.
    # Повторный запуск начинал с той же головы и не двигался дальше никогда.
    # Замер на копии боевой базы: 184 объекта без даты при batch=200 — сегодня
    # укладывается, но ровно поэтому дефект и не проявился ни разу; корпус растёт.
    cursor = 0
    try:
        while True:
            batch = storage.knowledge_missing_document_date(
                user_id=args.user, limit=args.batch, after_rowid=cursor
            )
            if not batch:
                break
            for row in batch:
                cursor = max(cursor, int(row["position"]))
                scanned += 1
                raw_path = str(row.get("stored_path") or "")
                path = pathlib.Path(raw_path)
                if not path.is_absolute():
                    path = settings.files_dir / path
                try:
                    content = path.read_bytes()
                except OSError:
                    missing += 1
                    continue
                if content[:2] == b"PK":
                    found = _office_document_date(content)
                elif content[:5] == b"%PDF-":
                    found = _pdf_document_date_from_bytes(content)
                else:
                    found = None
                if found and storage.set_document_date(str(row["id"]), str(row["user_id"]), found):
                    dated += 1
            if args.limit and scanned >= args.limit:
                break
        storage.record_event(
            "documents.dates_backfilled",
            {"scanned": scanned, "dated": dated, "files_missing": missing},
        )
    finally:
        storage.close()
    print(f"Просмотрено объектов: {scanned}; проставлено дат: {dated}; файлов не найдено: {missing}.")
    if scanned and not dated:
        print("Ни одной даты: у этих форматов её нет в файле — это не ошибка, а отсутствие данных.")
    return 0


def _backfill_entities(args: argparse.Namespace) -> int:
    """Провести ОБЪЯВЛЯЮЩЕЕ правило извлечения по УЖЕ загруженному архиву.

    Правило, добавленное после загрузки корпуса, на лежащие в базе документы не
    действует вовсе — извлечение работает только при приёме. Такой проход и есть
    способ это исправить.

    Метод называется явно и только один за прогон: остальные отработали при приёме,
    и повторный прогон по ним означал бы новое решение за человека там, где его уже
    спрашивали. Разрешены только ОБЪЯВЛЯЮЩИЕ методы (`DECLARED_ENTITY_METHODS`) —
    те, у которых есть право само создавать узел; догадка по форме слова таким
    правом не обладает и через этот проход пройти не должна.

    Чем уже пользовались:

      explicit_person_patronymic — ФИО с отчеством. Замер на 900 документах: 6094
        упоминания, 3069 различных ФИО; на всех 1532 объектах — 20 644 упоминания и
        4349 узлов, 71% имён встречается больше чем в одном документе, перестановочных
        двойников 4 из 4349. Точность 100% на 80 именах при судье, проверенном 6 из 6.

      explicit_military_unit — «в/ч N» и «войсковая часть N». Замер на живом архиве:
        240 документов, 151 различная часть, 67 из них более чем в одном документе,
        1079 пар «человек и часть» в пределах абзаца. До правила извлекалось НОЛЬ.

    По умолчанию — ПОКАЗ: считает и не пишет. Запись включает `--apply`.
    """
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.ingestion import _extract_entities
    from friday.ingestion._base import DECLARED_ENTITY_METHODS
    from friday.knowledge_graph import KnowledgeGraph
    from friday.storage import init_storage
    from friday.storage.models import EntityType

    method = str(args.method)
    if method not in DECLARED_ENTITY_METHODS:
        print(
            f"Метод {method!r} не объявляющий. Проход умеет только те, что вправе сами "
            f"создавать узел:\n  " + "\n  ".join(sorted(DECLARED_ENTITY_METHODS)),
            file=sys.stderr,
        )
        return 2

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    graph = KnowledgeGraph(storage)
    apply_changes = bool(getattr(args, "apply", False))
    scanned = mentions = created = linked = skipped_decided = 0
    names: set[str] = set()
    cursor = 0
    try:
        while True:
            batch = storage.knowledge_bodies_after(after_rowid=cursor, user_id=args.user, limit=args.batch)
            if not batch:
                break
            for row in batch:
                cursor = int(row["rowid"])
                scanned += 1
                ko_id, owner = str(row["id"]), str(row["user_id"])
                candidates = [
                    item
                    for item in _extract_entities(str(row["content"] or ""))
                    if str(item.get("method") or "") == method
                ]
                if not candidates:
                    continue
                decided = storage.decided_entity_links(owner, ko_id) if apply_changes else set()
                for candidate in candidates:
                    mentions += 1
                    name = str(candidate.get("name") or "").strip()
                    if not name:
                        continue
                    names.add(name.casefold())
                    if not apply_changes:
                        continue
                    entity = graph.find_entity(owner, name)
                    if not entity:
                        try:
                            entity = graph.create_entity(
                                owner,
                                name,
                                EntityType(str(candidate.get("entity_type") or EntityType.OTHER.value)),
                                metadata={
                                    "created_by": "backfill_entities",
                                    "extraction_method": method,
                                    "initial_confidence": float(candidate.get("confidence", 0.9)),
                                },
                            )
                            created += 1
                        except (ValueError, KeyError):
                            continue
                    if str(entity["id"]) in decided:
                        # Человек уже высказался про эту пару. Проход не спорит с ним.
                        skipped_decided += 1
                        continue
                    graph.link_knowledge_to_entity(
                        ko_id,
                        str(entity["id"]),
                        owner,
                        confidence=float(candidate.get("confidence", 0.9)),
                        evidence={
                            "method": method,
                            "matched_as": candidate.get("matched_as", name),
                            "backfill": True,
                        },
                        status="accepted",
                    )
                    linked += 1
            if args.limit and scanned >= args.limit:
                break
        if apply_changes:
            storage.record_event(
                "graph.entities_backfilled",
                {
                    "method": method,
                    "scanned": scanned,
                    "mentions": mentions,
                    "distinct_names": len(names),
                    "entities_created": created,
                    "links": linked,
                    "skipped_decided": skipped_decided,
                },
            )
    finally:
        storage.close()
    # «Упоминаний» здесь — это пары (документ, имя), а не вхождения в текст:
    # `_extract_entities` схлопывает одинаковые имена внутри документа. Отдельная проба
    # по сырому тексту даёт больше (1522 против 464 у частей), и это не расхождение,
    # а разные величины — путать их значит спорить с собственным замером.
    print(
        f"Метод: {method}. Просмотрено объектов: {scanned}; "
        f"пар документ-имя: {mentions}; различных имён: {len(names)}."
    )
    if apply_changes:
        print(
            f"Создано сущностей: {created}; связей знание-человек: {linked}; "
            f"обойдено решённых человеком: {skipped_decided}."
        )
    else:
        print("Это ПОКАЗ, в базу ничего не записано. Чтобы применить, повторите с --apply.")
    return 0


def _backfill_relations(args: argparse.Namespace) -> int:
    """Провести извлечение СВЯЗЕЙ по уже загруженному архиву.

    Та же беда, что у сущностей: правило действует только при приёме документа, а
    корпус загружен раньше. В графе владельца было 4610 сущностей и НОЛЬ связей —
    не потому, что механизм сломан, а потому, что его никто не звал.

    Замерено на копии базы 2026-08-03 (проход по всем 1533 документам):

        без родственных слов                      0 кандидатов
        со словами, без проверок             509 кандидатов, мусор: «Изобильный
                                             -> Москва | Брат» — два города
        + обе стороны люди                   243 кандидата, половина сцепляет
                                             людей из РАЗНЫХ анкет заголовком поля
        + слово вплотную к имени              98 кандидатов, из них 4 от «внук» —
                                             все из одного списка позывных
        + «внук» убран из словаря             94 кандидата на 56 документах,
                                             около 85% верных на глаз

    Результат — ОЧЕРЕДЬ НА ПОДТВЕРЖДЕНИЕ, а не готовые связи: каждый кандидат
    ждёт решения человека. Поэтому по умолчанию — показ, запись включает `--apply`.
    """
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.knowledge_graph import KnowledgeGraph
    from friday.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    graph = KnowledgeGraph(storage)
    apply_changes = bool(getattr(args, "apply", False))
    scanned = found = touched = 0
    #: Одна и та же пара, названная в трёх документах, — три СРАБАТЫВАНИЯ и одна
    #: связь: хранилище схлопывает их по (источник, цель, тип). Считать надо оба
    #: числа. Замерено: 94 срабатывания дали 64 различных пары, и печатать первое
    #: как «кандидатов в связи» значило бы выдать работу прохода за содержимое
    #: очереди — тот же класс, что «длина страницы — не факт о корпусе».
    pairs: set[str] = set()
    cursor = 0
    try:
        while True:
            batch = storage.knowledge_bodies_after(after_rowid=cursor, user_id=args.user, limit=args.batch)
            if not batch:
                break
            for row in batch:
                cursor = int(row["rowid"])
                scanned += 1
                if not apply_changes:
                    # Показ считает документы, а не кандидатов: сам разбор ПИШЕТ
                    # в базу, и «сухой» его вариант был бы вторым кодом, который
                    # мерит уже не то, что применится.
                    continue
                try:
                    made = graph.suggest_relations_for_knowledge(str(row["user_id"]), str(row["id"]))
                except Exception as error:  # noqa: BLE001 — один документ не должен рвать проход
                    print(f"  {row['id']}: {type(error).__name__}: {error}", file=sys.stderr)
                    continue
                if made:
                    found += len(made)
                    pairs.update(str(item.get("id") or "") for item in made if item.get("id"))
                    touched += 1
            if args.limit and scanned >= args.limit:
                break
        if apply_changes:
            storage.record_event(
                "graph.relations_backfilled",
                {
                    "scanned": scanned,
                    "matches": found,
                    "candidates": len(pairs),
                    "documents": touched,
                },
            )
    finally:
        storage.close()
    print(f"Просмотрено объектов: {scanned}.")
    if apply_changes:
        print(
            f"Срабатываний: {found}; различных пар в очереди: {len(pairs)}; "
            f"документов со связями: {touched}."
        )
        print("Это КАНДИДАТЫ — каждый ждёт подтверждения человеком в панели.")
    else:
        print("Это ПОКАЗ, в базу ничего не записано. Чтобы применить, повторите с --apply.")
    return 0


def _extract_structure_relations(args: argparse.Namespace) -> int:
    """Связи, объявленные ФОРМОЙ документа, — арбитром по всему архиву.

    Второй проход рядом с `backfill-relations`, а не замена ему. Фразовый ищет
    объявляющее слово между двумя именами и связывает эти два имени; форма
    служебного документа объявляет отношения СУБЪЕКТА — того, чья это анкета,
    чей это пункт списка, кто подписал рапорт. Замерено на архиве владельца: в
    рапорте из восьми фразовых пар верны три, и те случайно.

    Требуется модель: форм в архиве больше десятка (анкет 167, рапортов 5,
    прочего 1360 — ведомости, списки, книги, планы, выписки, листы Excel), и
    каждая новая форма при шаблонном разборе снова даёт ноль.

    Результат — ОЧЕРЕДЬ НА ПОДТВЕРЖДЕНИЕ. По умолчанию показ, запись включает
    `--apply`; показ здесь настоящий — арбитр вызывается с `store=False`.
    """
    import asyncio

    from friday.agent_runtime.llm import LLMRouter
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.knowledge_graph import KnowledgeGraph
    from friday.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    graph = KnowledgeGraph(storage)
    llm = LLMRouter(settings)
    if not llm.enabled:
        print("Модель выключена: разбор формы документа без неё невозможен.", file=sys.stderr)
        storage.close()
        return 2
    apply_changes = bool(getattr(args, "apply", False))

    async def run() -> tuple[int, int, int, int]:
        scanned = proposed = kept = skipped_windows = 0
        cursor = 0
        while True:
            batch = storage.knowledge_bodies_after(
                after_rowid=cursor, user_id=args.user, limit=args.batch
            )
            if not batch:
                break
            for row in batch:
                cursor = int(row["rowid"])
                scanned += 1
                try:
                    result = await graph.suggest_relations_from_structure(
                        str(row["user_id"]),
                        str(row["id"]),
                        llm=llm,
                        store=apply_changes,
                    )
                except Exception as error:  # noqa: BLE001 — один документ не рвёт проход
                    print(f"  {row['id']}: {type(error).__name__}: {error}", file=sys.stderr)
                    continue
                proposed += int(result.get("proposed") or 0)
                kept += len(result.get("candidates") or [])
                skipped_windows += int(result.get("windows_skipped") or 0)
            if args.limit and scanned >= args.limit:
                break
        return scanned, proposed, kept, skipped_windows

    try:
        scanned, proposed, kept, skipped_windows = asyncio.run(run())
        if apply_changes:
            storage.record_event(
                "graph.structure_relations_extracted",
                {"scanned": scanned, "proposed": proposed, "kept": kept},
            )
    finally:
        storage.close()
    print(f"Просмотрено объектов: {scanned}.")
    print(f"Арбитр предложил: {proposed}; прошло проверки: {kept}.")
    if skipped_windows:
        # Названо вслух: молча недочитанный документ выглядит как разобранный.
        print(f"НЕ прочитано окон (документы длиннее потолка): {skipped_windows}.")
    if apply_changes:
        print("Это КАНДИДАТЫ — каждый ждёт подтверждения человеком в панели.")
    else:
        print("Это ПОКАЗ, в базу ничего не записано. Чтобы применить, повторите с --apply.")
    return 0


def _resolve_exact_duplicates(args: argparse.Namespace) -> int:
    """Снять с очереди те конфликты, где решать нечего: текст совпал побайтово.

    Замерено на живом архиве 2026-08-03. В очереди «почти-дубликат» лежали 200
    пар, и разбор их состава показал:

        точные копии (текст совпал) ........  56
        версии (имя то же, текст другой) ...  54
        «разные» (имя и текст другие) ......  90   медиана похожести 0.99

    Все 200 пришли ОДНИМ импортом папки 29 июля, и ни одна из точных копий не
    ловилась дедупликацией по хешу файла: тот же документ, пересохранённый из
    Word, даёт другие байты. Двести решений система создала себе сама.

    Здесь закрываются ТОЛЬКО точные копии — там, где нормализованный текст
    совпадает знак в знак. Победителем остаётся более ранняя запись: повтор
    воспроизводит первое решение, а не последнее. Порог похожести не участвует
    вовсе — `friday/dedup.py` замерил, что «дубликат» и «следующая заметка в
    серии» перекрываются и порогом не разделяются, поэтому всё, что не совпало
    точно, остаётся человеку.

    По умолчанию — ПОКАЗ. Запись включает `--apply`.
    """
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.ingestion._base import _extracted_text_digest
    from friday.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    apply_changes = bool(getattr(args, "apply", False))
    exact = versions = different = 0
    closed = 0
    try:
        rows = storage.execute(
            """SELECT h.id, h.user_id, h.knowledge_a_id a, h.knowledge_b_id b,
                      ka.title ta, kb.title tb, ka.content ca, kb.content cb,
                      ka.created_at da, kb.created_at db
               FROM knowledge_conflicts h
               JOIN knowledge_objects ka ON ka.id=h.knowledge_a_id
               JOIN knowledge_objects kb ON kb.id=h.knowledge_b_id
               WHERE h.status='suggested' AND h.conflict_type='near_duplicate'"""
        ).fetchall()
        for row in rows:
            item = dict(row)
            if _extracted_text_digest(item["ca"]) != _extracted_text_digest(item["cb"]):
                if str(item["ta"]).strip() == str(item["tb"]).strip():
                    versions += 1
                else:
                    different += 1
                continue
            exact += 1
            if not apply_changes:
                continue
            # Более ранняя ЖИВАЯ запись — победитель. Проигравшая становится
            # `deprecated` штатным путём разрешения конфликта, а не удаляется:
            # у неё остаётся собственный провенанс, и откат возможен.
            #
            # Живая — потому что копии образуют КЛАСТЕРЫ. Найдено на живом
            # архиве: пять копий одного документа дают десять пар, и запись,
            # проигравшая в первой паре, во второй оказывается «более ранней».
            # Разрешение такой пары справедливо отвергается хранилищем («winner
            # is already deprecated»), и проход падал на 55-й паре из 56.
            owner = str(item["user_id"])
            sides = sorted(
                ((str(item["da"]), str(item["a"])), (str(item["db"]), str(item["b"]))),
            )
            alive = [
                ko_id
                for _when, ko_id in sides
                if str((storage.get_knowledge_object(ko_id, owner) or {}).get("lifecycle_stage") or "")
                != "deprecated"
            ]
            if not alive:
                # Обе стороны уже погашены другими парами кластера — решать
                # нечего, но и висеть в очереди пара не должна.
                #
                # Найдено на живом архиве, уже ПОСЛЕ первой правки: пропуск через
                # `continue` оставлял такую пару в статусе `suggested` навсегда.
                # Проход печатал «точных копий: 1» и закрывал ноль — вечный
                # хвост, который человек всё равно не смог бы разобрать: обе
                # записи погашены, выбирать не из чего.
                if storage.review_knowledge_conflict(
                    owner,
                    str(item["id"]),
                    "dismissed",
                    reviewed_by="exact_duplicate_pass",
                    resolution_note="обе записи уже погашены как копии в этом же кластере",
                ):
                    closed += 1
                continue
            try:
                if storage.resolve_conflict(
                    owner,
                    str(item["id"]),
                    alive[0],
                    reviewed_by="exact_duplicate_pass",
                    resolution_note="точная копия: извлечённый текст совпал знак в знак",
                ):
                    closed += 1
            except Exception as error:  # noqa: BLE001 — одна пара не должна рвать проход
                print(f"  {item['id']}: {type(error).__name__}: {error}", file=sys.stderr)
        if apply_changes and closed:
            storage.record_event(
                "knowledge.exact_duplicates_resolved",
                {"closed": closed, "exact": exact, "versions": versions, "different": different},
            )
    finally:
        storage.close()
    print(f"Конфликтов «почти-дубликат» в очереди: {len(rows)}.")
    print(f"  точные копии (решать нечего): {exact}")
    print(f"  версии одного имени:          {versions}   <- остаются человеку")
    print(f"  прочие:                       {different}   <- остаются человеку")
    if apply_changes:
        print(f"\nЗакрыто как точные копии: {closed}. Проигравшая запись помечена устаревшей, не удалена.")
    else:
        print("\nЭто ПОКАЗ, в базу ничего не записано. Чтобы применить, повторите с --apply.")
    return 0


def _purge(args: argparse.Namespace) -> int:
    """Irreversibly hard-delete soft-deleted knowledge while the backend is stopped."""

    if not args.yes:
        print(
            "Purge необратимо уничтожает объекты, версии, raw-файлы, vault-копии и graph-links. "
            "Повторите с --yes после остановки backend и Telegram bridge.",
            file=sys.stderr,
        )
        return 2

    from friday.config import ensure_runtime_dirs, load_settings
    from friday.diagnostics.runtime_lease import ProcessLease
    from friday.memory import MemoryVault
    from friday.purge import purge_knowledge
    from friday.storage import init_storage
    from friday.storage.models import AuditEntry, new_id

    settings = load_settings()
    ensure_runtime_dirs(settings)
    with ProcessLease(settings.state_dir / "backend.lock", protocol="friday.backend.v1"):
        storage = init_storage(settings)
        try:
            vault = MemoryVault(settings.memory_vault_dir)
            if args.id:
                # `--user` scopes the purge when given; without it, resolve the
                # object's real owner. Defaulting to LEGACY_OWNER_USER_ID meant
                # `--id` silently searched only the owner tenant while `--user`'s own
                # help promises "all tenants for batch", so purging anyone else's
                # object reported "Объект не найден." and the object stayed forever.
                owner = args.user
                if not owner:
                    existing = storage.get_knowledge_object(args.id)
                    if existing is None:
                        print("Объект не найден.", file=sys.stderr)
                        return 2
                    owner = str(existing.get("user_id") or "")
                    print(f"Объект принадлежит арендатору {owner}.")
                try:
                    report = purge_knowledge(storage, settings, vault, args.id, owner)
                except ValueError as exc:
                    print(str(exc), file=sys.stderr)
                    return 2
                if not report.get("existed"):
                    print("Объект не найден.", file=sys.stderr)
                    return 2
                results = [report]
            else:
                days = (
                    args.older_than_days
                    if args.older_than_days is not None
                    else settings.purge_retention_days
                )
                candidates = storage.list_purgeable_knowledge(
                    args.user, older_than_days=days, limit=args.limit
                )
                results = [
                    purge_knowledge(storage, settings, vault, cand["id"], cand["user_id"])
                    for cand in candidates
                ]
            for report in results:
                storage.log_audit(
                    AuditEntry(
                        id=new_id("audit"),
                        user_id=str(report.get("user_id") or ""),
                        action="cli.knowledge.purge",
                        target_type="knowledge_object",
                        target_id=str(report.get("knowledge_object_id") or ""),
                        before_json=None,
                        after_json=report,
                        ip_address="",
                        request_id="cli",
                    )
                )
        finally:
            storage.close()
    _json_print({"purged": len(results), "items": results})
    return 0


def _mint_token(args: argparse.Namespace) -> int:
    """Issue a scoped API token bound to an account/preset (bootstrap path)."""

    import hashlib
    import secrets

    from friday.config import ensure_runtime_dirs, load_settings
    from friday.permissions import BUILTIN_PRESET_KEYS
    from friday.storage import init_storage, validate_user_id

    preset = args.preset
    if preset and preset not in BUILTIN_PRESET_KEYS:
        print(
            f"Неизвестный preset: {preset}. Допустимо: {', '.join(sorted(BUILTIN_PRESET_KEYS))}.",
            file=sys.stderr,
        )
        return 2

    ttl_seconds: int | None = None
    if getattr(args, "ttl", None):
        try:
            ttl_seconds = _parse_ttl_seconds(args.ttl)
        except ValueError:
            print(f"Некорректный --ttl: {args.ttl!r}. Примеры: 90d, 24h, 30m, 3600s.", file=sys.stderr)
            return 2

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        try:
            user_id = validate_user_id(args.user)
        except ValueError as exc:
            print(str(exc), file=sys.stderr)
            return 2
        storage.ensure_user(
            user_id,
            source="api-token",
            display_name=args.user,
            preset_key=preset or "user",
        )
        # ensure_user never changes an existing account's preset; apply it explicitly.
        if preset:
            storage.update_user(user_id, preset_key=preset)
        current = storage.get_user(user_id) or {}
        secret = "jrc_" + secrets.token_urlsafe(32)
        token_hash = hashlib.sha256(secret.encode("utf-8")).hexdigest()
        record = storage.create_api_token(
            user_id,
            token_hash,
            label=args.label or "",
            created_by="cli",
            ttl_seconds=ttl_seconds,
        )
    finally:
        storage.close()
    _json_print(
        {
            "id": record.get("id"),
            "user_id": user_id,
            "preset": current.get("preset_key"),
            "label": args.label or "",
            "expires_at": record.get("expires_at"),
        }
    )
    print(f"API-токен (показывается один раз): {secret}", file=sys.stderr)
    return 0


def _revoke_token(args: argparse.Namespace) -> int:
    from friday.config import ensure_runtime_dirs, load_settings
    from friday.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        revoked = storage.revoke_api_token(args.token_id)
    finally:
        storage.close()
    if not revoked:
        print("Токен не найден или уже отозван.", file=sys.stderr)
        return 2
    _json_print({"status": "revoked", "id": args.token_id})
    return 0


def _run_telegram_bridge() -> int:
    from friday.config import ensure_runtime_dirs, load_settings, validate_settings
    from friday.telegram_bridge import TelegramBridge, TelegramConfig

    settings = load_settings()
    ensure_runtime_dirs(settings)
    # Surface deny-by-default and credential problems as a clear CLI error before
    # the bridge starts, since validate_settings is otherwise only run by the
    # backend process.
    problems = validate_settings(settings, production=not settings.is_loopback_bind)
    fatal = [item for item in problems if not item.startswith("warning:")]
    if fatal:
        raise ValueError("Invalid Friday configuration: " + "; ".join(fatal))
    token = config_env("FRIDAY_TELEGRAM_BOT_TOKEN", "").strip()
    # This compares configured bind literals; it does not open a listener.
    host = (
        "127.0.0.1"  # nosec B104
        if settings.api_host in {"0.0.0.0", "::", "localhost"}  # nosec B104
        else settings.api_host
    )
    config = TelegramConfig(
        bot_token=token,
        backend_url=config_env(
            "FRIDAY_BACKEND_URL",
            f"http://{host}:{settings.api_port}",
        ).rstrip("/"),
        bridge_secret=settings.telegram_bridge_secret,
        allowed_chat_ids=settings.telegram_effective_allowed_chat_ids,
        inbox_db_path=str(settings.state_dir / "telegram-inbox.sqlite3"),
        max_document_bytes=settings.max_upload_bytes,
        backend_timeout_sec=max(30.0, settings.llm_timeout_sec + 30.0),
        telegram_proxy=settings.telegram_proxy,
        open_registration=settings.telegram_open_registration,
        # Outbound delivery polls faster than the reminder scan so a queued
        # message reaches the user promptly rather than on the next scan.
    )
    bridge = TelegramBridge(config)
    try:
        asyncio.run(bridge.run())
    except KeyboardInterrupt:
        print("\nTelegram bridge остановлен.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="jericho",
        description="Local-first personal Knowledge Operating System",
    )
    parser.add_argument("--version", action="version", version=f"Friday {__version__}")
    parser.add_argument("--log-level", default=config_env("FRIDAY_LOG_LEVEL", "INFO"))
    parser.add_argument(
        "--env-file",
        help="Load configuration from this .env file (default: ./.env.local)",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    init = sub.add_parser("init", help="Create runtime directories and a private .env.local")
    init.add_argument("--home", help="Override FRIDAY_HOME for the generated configuration")
    init.add_argument("--force", action="store_true", help="Replace an existing environment file")
    init.set_defaults(handler=_init_environment)

    server = sub.add_parser("server", help="Start the API and Admin UI")
    server.set_defaults(handler=lambda _: _run_server())

    telegram = sub.add_parser("telegram-bridge", help="Start durable Telegram long polling")
    telegram.set_defaults(handler=lambda _: _run_telegram_bridge())

    up = sub.add_parser("up", help="Validate config, then run backend (+bridge) under supervision")
    up.add_argument("--no-bridge", action="store_true", help="Do not start the Telegram bridge")
    up.set_defaults(handler=_up)

    tui = sub.add_parser("tui", help="Interactive launcher: configure the LLM endpoint/token, start, status")
    tui.set_defaults(handler=_tui)

    services = sub.add_parser("install-services", help="Generate systemd --user units for backend and bridge")
    services.add_argument("--dir", help="Target directory (default: ~/.config/systemd/user)")
    services.set_defaults(handler=_install_services)

    status = sub.add_parser("status", help="Show concise local status")
    status.add_argument("--json", action="store_true")
    status.add_argument("--check-llm", action="store_true")
    status.set_defaults(handler=_status)

    doctor = sub.add_parser("doctor", help="Run detailed diagnostics")
    doctor.add_argument("--check-llm", action="store_true")
    doctor.set_defaults(handler=_doctor)

    backup = sub.add_parser("backup", help="Create and integrity-check an online SQLite backup")
    backup.add_argument("--label", default="cli")
    backup.set_defaults(handler=_backup)

    keygen = sub.add_parser("backup-keygen", help="Generate the backup-encryption key file")
    keygen.add_argument("--out", help="Key file path (default: FRIDAY_BACKUP_ENCRYPTION_KEY_FILE)")
    keygen.add_argument("--force", action="store_true", help="Replace an existing key file")
    keygen.set_defaults(handler=_backup_keygen)

    decrypt = sub.add_parser("decrypt-backup", help="Decrypt an .enc mirror copy for restore")
    decrypt.add_argument("filename", help="Encrypted backup file (…sqlite3.enc)")
    decrypt.add_argument("--out", help="Output path (default: strip .enc)")
    decrypt.add_argument("--key", help="Key file (default: FRIDAY_BACKUP_ENCRYPTION_KEY_FILE)")
    decrypt.set_defaults(handler=_decrypt_backup)

    verify = sub.add_parser("verify-backup", help="Verify one backup (or the newest one)")
    verify.add_argument("filename", nargs="?")
    verify.set_defaults(handler=_verify_backup)

    restore = sub.add_parser(
        "restore-backup",
        help="Atomically restore a verified SQLite backup while Friday is stopped",
    )
    restore.add_argument("filename", nargs="?", help="Backup filename (default: newest manifest)")
    restore.add_argument(
        "--yes",
        action="store_true",
        help="Confirm replacement of the active database and creation of a safety backup",
    )
    restore.set_defaults(handler=_restore_backup)

    export = sub.add_parser("export-user", help="Export one tenant's data as JSON")
    export.add_argument("user_id")
    export.set_defaults(handler=_export_user)

    events = sub.add_parser("events", help="Operational journal: what happened while you were away")
    events.add_argument("--type", help="Only this event type, e.g. worker.failed")
    events.add_argument("--limit", type=int, default=50, help="How many to show (newest first)")
    events.add_argument("--json", action="store_true", help="Machine-readable output")
    events.set_defaults(handler=_events)

    source = sub.add_parser(
        "search-source",
        help="Search the original ingested text (not the knowledge derived from it)",
    )
    source.add_argument("query", help="Phrase to look for in source documents")
    source.add_argument("--user", help="Target account (default: the owner)")
    source.add_argument("--limit", type=int, default=20, help="How many sources to show")
    source.add_argument("--json", action="store_true", help="Machine-readable output")
    source.set_defaults(handler=_search_source)

    bootstrap = sub.add_parser(
        "eval-bootstrap",
        help="Draft retrieval gold cases from existing knowledge using the model",
    )
    bootstrap.add_argument("--user", help="Target account (default: the only one, if there is one)")
    bootstrap.add_argument("--limit", type=int, default=20, help="How many cases to draft")
    bootstrap.add_argument("--save", action="store_true", help="Persist the accepted cases")
    bootstrap.set_defaults(handler=_eval_bootstrap)

    model_check = sub.add_parser(
        "model-check",
        help="Probe the configured LLM endpoint by generating, not just connecting",
    )
    model_check.add_argument("--json", action="store_true", help="Machine-readable report")
    model_check.add_argument("--timeout", type=float, default=60.0, help="Per-request timeout, seconds")
    model_check.set_defaults(handler=_model_check)

    importer = sub.add_parser(
        "import",
        help="Import a directory of files; everything lands in the Inbox for review",
    )
    importer.add_argument("path", help="Directory (or single file) to import")
    importer.add_argument("--user", help="Target account (default: the only one, if there is one)")
    importer.add_argument(
        "--dry-run", action="store_true", help="Show what would be imported and write nothing"
    )
    importer.add_argument(
        "--suffix",
        action="append",
        metavar=".md",
        help="Only these extensions; repeatable. Default: every file type",
    )
    importer.add_argument(
        "--limit", type=int, default=None, help="Stop after this many files (the walk is ordered)"
    )
    importer.add_argument("--include-hidden", action="store_true", help="Include dotfiles and dotdirs")
    importer.add_argument("--follow-symlinks", action="store_true", help="Follow symlinks while walking")
    importer.add_argument("--quiet", action="store_true", help="Only report failures and the summary")
    importer.set_defaults(handler=_import)

    purge = sub.add_parser(
        "purge",
        help="Hard-delete soft-deleted knowledge (rows, versions, FTS, raw file, vault) while stopped",
    )
    purge.add_argument("--id", help="Purge one specific knowledge object id (must be soft-deleted)")
    purge.add_argument("--user", help="Restrict to one tenant (default: all tenants for batch)")
    purge.add_argument(
        "--older-than-days",
        type=int,
        default=None,
        help="Retention window; only purge objects soft-deleted at least this long ago",
    )
    purge.add_argument("--limit", type=int, default=200, help="Maximum objects to purge in one run")
    purge.add_argument("--yes", action="store_true", help="Confirm irreversible destruction")
    purge.set_defaults(handler=_purge)

    reindex = sub.add_parser(
        "reindex-embeddings",
        help="Mark stored vectors stale so the indexer recomputes them (search keeps working)",
    )
    reindex.add_argument("--user", help="Restrict to one tenant (default: every tenant)")
    reindex.add_argument("--yes", action="store_true", help="Confirm the recomputation")
    reindex.set_defaults(handler=_reindex_embeddings)

    backfill = sub.add_parser(
        "backfill-document-dates",
        help="Read each stored file's own date (Office/PDF metadata) into its Knowledge Object",
    )
    backfill.add_argument("--user", help="Restrict to one tenant (default: every tenant)")
    backfill.add_argument("--batch", type=int, default=200, help="Objects per pass (default: 200)")
    backfill.add_argument("--limit", type=int, default=0, help="Stop after N objects (default: no limit)")
    backfill.set_defaults(handler=_backfill_document_dates)

    entities = sub.add_parser(
        "backfill-entities",
        help="Run one declaring extraction rule over the archive ingested before it existed",
    )
    entities.add_argument(
        "--method",
        required=True,
        help="Declaring extraction method, e.g. explicit_person_patronymic or explicit_military_unit",
    )
    entities.add_argument("--user", help="Restrict to one tenant (default: every tenant)")
    entities.add_argument("--batch", type=int, default=200, help="Objects per pass (default: 200)")
    entities.add_argument("--limit", type=int, default=0, help="Stop after N objects (default: no limit)")
    entities.add_argument(
        "--apply",
        action="store_true",
        help="Write the entities and links (without it the pass only counts)",
    )
    entities.set_defaults(handler=_backfill_entities)

    relations = sub.add_parser(
        "backfill-relations",
        help="Extract declared relations over the archive ingested before the rule existed",
    )
    relations.add_argument("--user", help="Restrict to one tenant (default: every tenant)")
    relations.add_argument("--batch", type=int, default=200, help="Objects per pass (default: 200)")
    relations.add_argument("--limit", type=int, default=0, help="Stop after N objects (default: no limit)")
    relations.add_argument(
        "--apply",
        action="store_true",
        help="Write the relation candidates (without it the pass only counts objects)",
    )
    relations.set_defaults(handler=_backfill_relations)

    structure = sub.add_parser(
        "extract-structure-relations",
        help="Extract relations declared by document FORM (questionnaire field, roster row, report addressee)",
    )
    structure.add_argument("--user", help="Restrict to one tenant (default: every tenant)")
    structure.add_argument("--batch", type=int, default=50, help="Objects per pass (default: 50)")
    structure.add_argument("--limit", type=int, default=0, help="Stop after N objects (default: no limit)")
    structure.add_argument(
        "--apply",
        action="store_true",
        help="Write the relation candidates (without it the pass only shows them)",
    )
    structure.set_defaults(handler=_extract_structure_relations)

    duplicates = sub.add_parser(
        "resolve-exact-duplicates",
        help="Close near-duplicate conflicts whose extracted text matches exactly",
    )
    duplicates.add_argument(
        "--apply",
        action="store_true",
        help="Close them (without it the pass only counts and shows the split)",
    )
    duplicates.set_defaults(handler=_resolve_exact_duplicates)

    mint = sub.add_parser("mint-token", help="Issue a scoped API token for an account/preset")
    mint.add_argument("--user", required=True, help="Account id the token authenticates as")
    mint.add_argument("--preset", help="Set the account preset (owner/admin/moderator/user/guest)")
    mint.add_argument("--label", help="Human-readable label for the token")
    mint.add_argument("--ttl", help="Token lifetime, e.g. 90d, 24h, 30m, 3600s (default: no expiry)")
    mint.set_defaults(handler=_mint_token)

    revoke = sub.add_parser("revoke-token", help="Revoke a previously issued API token by id")
    revoke.add_argument("token_id")
    revoke.set_defaults(handler=_revoke_token)
    return parser


def _run_server() -> int:
    from friday.server import run_server

    run_server()
    return 0


def _tui(args: argparse.Namespace) -> int:
    """Launch the interactive pseudographic launcher."""
    from friday.tui import run

    return run(args)


def _up(args: argparse.Namespace) -> int:
    """One-command launch: validate config, then supervise backend (+bridge)."""
    import sys

    from friday.config import ensure_runtime_dirs, load_settings, validate_settings
    from friday.diagnostics.runtime_lease import inspect_process_lease
    from friday.supervisor import ChildSpec, Supervisor

    settings = load_settings()
    ensure_runtime_dirs(settings)
    problems = validate_settings(settings, production=not settings.is_loopback_bind)
    errors = [item for item in problems if not item.startswith("warning:")]
    for problem in problems:
        print(("⚠ " if problem.startswith("warning:") else "✖ ") + problem)
    if errors:
        print("Конфигурация не готова — исправьте ошибки выше (.env.local).")
        return 2

    backend_lease = inspect_process_lease(settings.state_dir / "backend.lock", protocol="friday.backend.v1")
    if backend_lease.get("active"):
        print(f"Backend уже запущен (pid {backend_lease.get('pid')}). Второй не нужен.")
        return 2

    env_file = config_env("FRIDAY_ENV_FILE", "")
    base_argv = [sys.executable, "-m", "friday.cli"]
    if env_file:
        base_argv += ["--env-file", env_file]

    children = [
        ChildSpec(
            name="backend",
            argv=[*base_argv, "server"],
            log_path=settings.log_dir / "backend.log",
            cwd=settings.home,
        )
    ]
    bot_token = config_env("FRIDAY_TELEGRAM_BOT_TOKEN", "").strip()
    if args.no_bridge:
        print("Мост Telegram пропущен (--no-bridge).")
    elif not bot_token:
        print("Мост Telegram пропущен: FRIDAY_TELEGRAM_BOT_TOKEN не задан.")
    else:
        children.append(
            ChildSpec(
                name="telegram-bridge",
                argv=[*base_argv, "telegram-bridge"],
                log_path=settings.log_dir / "telegram-bridge.log",
                cwd=settings.home,
            )
        )

    print(f"Запускаю {', '.join(child.name for child in children)}; логи в {settings.log_dir}")
    print("Остановка: Ctrl+C (дети получают SIGTERM и завершаются штатно).")
    return Supervisor(
        children,
        log_max_bytes=settings.log_max_bytes,
        log_backups=settings.log_backups,
    ).run()


_SYSTEMD_UNIT_TEMPLATE = """[Unit]
Description=Friday {role}
After=network-online.target{after_extra}

[Service]
Type=simple
ExecStart={exec_start}
Restart=on-failure
RestartSec=5
{environment}WorkingDirectory={workdir}

[Install]
WantedBy=default.target
"""


def _install_services(args: argparse.Namespace) -> int:
    """Generate systemd --user units; printing, not enabling — the user decides."""
    import sys

    from friday.config import load_settings

    settings = load_settings()
    target_dir = Path(args.dir or Path.home() / ".config" / "systemd" / "user").expanduser()
    target_dir.mkdir(parents=True, exist_ok=True)

    env_file = config_env("FRIDAY_ENV_FILE", "")
    env_arg = f" --env-file {env_file}" if env_file else ""
    environment = f"Environment=FRIDAY_HOME={settings.home}\n"

    units: list[tuple[str, str]] = []
    units.append(
        (
            "jericho-backend.service",
            _SYSTEMD_UNIT_TEMPLATE.format(
                role="backend (API + Admin UI)",
                after_extra="",
                exec_start=f"{sys.executable} -m friday.cli{env_arg} server",
                environment=environment,
                workdir=settings.home,
            ),
        )
    )
    units.append(
        (
            "jericho-bridge.service",
            _SYSTEMD_UNIT_TEMPLATE.format(
                role="Telegram bridge",
                after_extra=" jericho-backend.service",
                exec_start=f"{sys.executable} -m friday.cli{env_arg} telegram-bridge",
                environment=environment,
                workdir=settings.home,
            ),
        )
    )
    for name, content in units:
        (target_dir / name).write_text(content, encoding="utf-8")
        print(f"Записан {target_dir / name}")
    if sys.executable.startswith(("/tmp/", "/var/tmp/")):
        print(
            "⚠ ExecStart указывает на временный Python-интерпретатор. Установите Friday в "
            "постоянный venv и перегенерируйте юниты перед enable."
        )
    print()
    print("Дальше (мост включайте только с настроенным FRIDAY_TELEGRAM_BOT_TOKEN):")
    print("  systemctl --user daemon-reload")
    print("  systemctl --user enable --now jericho-backend")
    print("  systemctl --user enable --now jericho-bridge")
    print("  loginctl enable-linger $USER   # чтобы сервисы жили без активной сессии")
    return 0


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    if args.env_file:
        os.environ["FRIDAY_ENV_FILE"] = str(Path(args.env_file).expanduser().resolve())
    # Load local secrets before installing formatters, otherwise early startup
    # failures could render credential-bearing values without exact redaction.
    from friday.config import load_local_env_file

    load_local_env_file()
    configure_logging(args.log_level)
    try:
        code = int(args.handler(args) or 0)
    except (ValueError, RuntimeError, FileNotFoundError) as exc:
        logging.getLogger(__name__).error("%s", exc)
        code = 2
    raise SystemExit(code)


if __name__ == "__main__":
    main()
