"""Promoting a row twice must return the SAME object, not build a second one.

Two paths clear `knowledge_object_id` and soft-delete the object while leaving the
row promotable again: «Игнорировать», and «Вернуть в Inbox» from the safe revision
screen — which the UI presents as reversible. Promoting afterwards re-entered
`_create_promoted_ko`, which reads only the raw text and the row's deterministic
suggestions and never looks at the object a human already curated. So the title,
summary and tags the reviewer typed were replaced by autogenerated ones, the object
got a fresh id, and its versions, entity links, usage history and embeddings stayed
stranded on a row that nothing lists — recoverable only by reading the audit log.

Reproduced adversarially through the real admin HTTP API before the fix. The claim
needed two corrections, both reflected here: the reviewer's arguments still win if
they retype, and the row's `suggested_tags_json` survives — it is simply never read.
What was lost is the identity of the object and everything hanging off it.
"""

from __future__ import annotations

import pytest

from friday.ingestion import IngestionPipeline
from friday.knowledge_graph import KnowledgeGraph
from friday.storage.models import InboxStatus


@pytest.fixture
def pipeline(settings, storage):
    return IngestionPipeline(settings, storage, KnowledgeGraph(storage))


@pytest.fixture
def reviewed(storage, pipeline):
    """A row a human has already promoted, with fields they typed themselves."""
    import asyncio

    storage.ensure_user("alice")
    content = "Проект Orion переходит на PostgreSQL 16. Решение принято на встрече с Петровым."
    result = asyncio.run(
        pipeline.ingest_text("alice", content, source="telegram", source_ref="orion-1", force_review=True)
    )
    inbox_id = str(result["inbox_id"])

    first = pipeline.classify_inbox_item(
        "alice",
        inbox_id,
        InboxStatus.CLASSIFIED,
        reviewed_by="alice",
        promote=True,
        title="Миграция Orion на PG16 — согласовано с Петровым",
        summary="Согласовано, срок — конец квартала.",
        tags=["миграция", "решение-встречи"],
    )
    return inbox_id, str(first["knowledge_object_id"])


def test_ignoring_then_promoting_again_returns_the_same_object(reviewed, pipeline, storage):
    inbox_id, first_id = reviewed

    pipeline.classify_inbox_item("alice", inbox_id, InboxStatus.IGNORED, reviewed_by="alice")
    assert storage.get_knowledge_object(first_id, "alice")["deleted_at"] is not None

    again = pipeline.classify_inbox_item(
        "alice", inbox_id, InboxStatus.CLASSIFIED, reviewed_by="alice", promote=True
    )
    assert again["knowledge_object_id"] == first_id, (
        "a second Knowledge Object was minted; the curated one is unreachable"
    )


def test_what_the_reviewer_typed_survives_the_round_trip(reviewed, pipeline, storage):
    inbox_id, first_id = reviewed

    pipeline.classify_inbox_item("alice", inbox_id, InboxStatus.IGNORED, reviewed_by="alice")
    pipeline.classify_inbox_item("alice", inbox_id, InboxStatus.CLASSIFIED, reviewed_by="alice", promote=True)

    restored = storage.get_knowledge_object(first_id, "alice")
    assert restored["deleted_at"] is None
    assert restored["title"] == "Миграция Orion на PG16 — согласовано с Петровым"
    assert "Согласовано" in (restored["summary"] or "")


def test_the_object_is_findable_again(reviewed, pipeline, storage):
    inbox_id, first_id = reviewed
    pipeline.classify_inbox_item("alice", inbox_id, InboxStatus.IGNORED, reviewed_by="alice")
    assert (
        storage.get_knowledge_by_raw(
            storage.get_knowledge_object(first_id, "alice")["raw_object_id"], "alice"
        )
        is None
    )

    pipeline.classify_inbox_item("alice", inbox_id, InboxStatus.CLASSIFIED, reviewed_by="alice", promote=True)
    live = storage.get_knowledge_by_raw(
        storage.get_knowledge_object(first_id, "alice")["raw_object_id"], "alice"
    )
    assert live and live["id"] == first_id


def test_only_one_object_ever_exists_for_the_raw_material(reviewed, pipeline, storage):
    inbox_id, first_id = reviewed
    raw_id = storage.get_knowledge_object(first_id, "alice")["raw_object_id"]

    for _ in range(3):
        pipeline.classify_inbox_item("alice", inbox_id, InboxStatus.IGNORED, reviewed_by="alice")
        pipeline.classify_inbox_item(
            "alice", inbox_id, InboxStatus.CLASSIFIED, reviewed_by="alice", promote=True
        )

    rows = storage.execute(
        "SELECT id, deleted_at FROM knowledge_objects WHERE raw_object_id=?", (raw_id,)
    ).fetchall()
    assert len(rows) == 1, f"three round trips left {len(rows)} objects on one Raw Object"
    assert rows[0]["deleted_at"] is None


def test_the_ignore_verdict_becomes_history_not_a_current_label(reviewed, pipeline, storage):
    """A live object still marked «ignored» would make its own provenance lie."""
    inbox_id, first_id = reviewed
    pipeline.classify_inbox_item("alice", inbox_id, InboxStatus.IGNORED, reviewed_by="alice")
    pipeline.classify_inbox_item("alice", inbox_id, InboxStatus.CLASSIFIED, reviewed_by="alice", promote=True)

    import json

    metadata = json.loads(storage.get_knowledge_object(first_id, "alice")["metadata_json"])
    assert "ignored_from_inbox" not in metadata
    assert metadata["restored_from_inbox"] == inbox_id
    assert any("ignored by" in entry for entry in metadata["review_history"])


def test_a_reviewer_who_retypes_still_wins(reviewed, pipeline, storage):
    inbox_id, first_id = reviewed
    pipeline.classify_inbox_item("alice", inbox_id, InboxStatus.IGNORED, reviewed_by="alice")
    pipeline.classify_inbox_item(
        "alice",
        inbox_id,
        InboxStatus.CLASSIFIED,
        reviewed_by="alice",
        promote=True,
        title="Новый заголовок от ревьюера",
    )
    assert storage.get_knowledge_object(first_id, "alice")["title"] == "Новый заголовок от ревьюера"


def test_ignoring_alone_still_removes_it_from_retrieval(reviewed, pipeline, storage):
    """Revival must happen only on an explicit re-promotion, never as a side effect."""
    inbox_id, first_id = reviewed
    pipeline.classify_inbox_item("alice", inbox_id, InboxStatus.IGNORED, reviewed_by="alice")

    stored = storage.get_knowledge_object(first_id, "alice")
    assert stored["deleted_at"] is not None
    assert storage.get_inbox_item(inbox_id, "alice")["knowledge_object_id"] is None
