"""Command-line operations for Jericho."""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import secrets
import sys
import tempfile
from contextlib import suppress
from pathlib import Path
from typing import Any

from jericho import __version__


def configure_logging(level: str = "INFO") -> None:
    from jericho.telemetry.logging import configure_secure_logging, secrets_from_environment

    configure_secure_logging(level, secrets_from_environment())


def _settings():
    from jericho.config import load_settings

    return load_settings()


def _json_print(value: Any) -> None:
    print(json.dumps(value, ensure_ascii=False, indent=2, default=str))


def _write_private_text_atomic(path: Path, content: str) -> None:
    """Replace a local secret file atomically without following a target symlink."""

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        raise ValueError(f"Refusing to write configuration through a symlink: {path}")
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=path.parent,
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        with suppress(OSError):
            temporary.chmod(0o600)
        os.replace(temporary, path)
        with suppress(OSError):
            path.chmod(0o600)
    finally:
        temporary.unlink(missing_ok=True)


def _init_environment(args: argparse.Namespace) -> int:
    if args.home:
        os.environ["JERICHO_HOME"] = str(Path(args.home).expanduser().resolve())
    from jericho.config import ensure_runtime_dirs, load_settings

    settings = load_settings()
    ensure_runtime_dirs(settings)
    target = Path(args.env_file or Path.cwd() / ".env.local").expanduser()
    if not target.is_absolute():
        target = Path.cwd() / target
    target = target.absolute()
    if target.is_symlink():
        print(f"Отказываюсь писать конфигурацию через symlink: {target}", file=sys.stderr)
        return 2
    if target.exists() and not args.force:
        print(f"Не перезаписываю существующий файл: {target}")
        print("Используйте --force только если осознанно хотите заменить локальные секреты.")
        return 2
    api_token = secrets.token_urlsafe(48)
    bridge_secret = secrets.token_urlsafe(48)
    content = f"""# Generated by `jericho init`. Keep this file private.
JERICHO_HOME={settings.home}
JERICHO_PROFILE=qwen36-vl
JERICHO_MODEL_ROOT={settings.model_root}

JERICHO_LLM_BASE_URL=http://127.0.0.1:8001/v1
JERICHO_LLM_MODEL=dispatcher
JERICHO_LLM_ENABLED=1
JERICHO_VERIFY_ANSWERS=1
# Semantic search: point at a SEPARATE local OpenAI-compatible /embeddings service
# (the chat vLLM above does not serve embeddings). Leave disabled to run on
# lexical+FTS+graph retrieval only.
JERICHO_EMBEDDINGS_ENABLED=0
JERICHO_EMBEDDINGS_BASE_URL=http://127.0.0.1:8002/v1
JERICHO_EMBEDDINGS_MODEL=
# Near-duplicate Knowledge Object detection (needs embeddings). Cosine >= this
# flags a likely duplicate as a review-gated conflict; resolve = deprecate one.
JERICHO_DEDUP_THRESHOLD=0.92
JERICHO_DEDUP_INTERVAL_SEC=21600
# Retrieval-quality eval over the gold set: recall@k measured periodically,
# regression vs the previous run logged. Curate cases in the admin Quality view.
JERICHO_EVAL_ENABLED=1
JERICHO_EVAL_INTERVAL_SEC=86400
JERICHO_EVAL_K=10
# Local speech-to-text for voice notes. Needs the optional extra:
# pip install 'jericho[voice]'. Runs fully offline; transcripts are
# model-generated, so they wait in the Inbox (no KO) until you confirm.
# Leave disabled to keep audio as un-extractable media. Empty language = auto.
JERICHO_WHISPER_ENABLED=0
JERICHO_WHISPER_MODEL=small
JERICHO_WHISPER_DEVICE=cpu
JERICHO_WHISPER_COMPUTE_TYPE=int8
JERICHO_WHISPER_LANGUAGE=
JERICHO_WHISPER_MAX_AUDIO_SEC=900
# Retention window (days) before a soft-deleted object is eligible for `jericho purge`.
JERICHO_PURGE_RETENTION_DAYS=30
# Offsite mirror for verified backups (external disk / synced folder).
# A same-disk backup is NOT a real backup. Empty = mirroring off.
JERICHO_BACKUP_MIRROR_DIR=
# Encrypt mirror copies (AES-256 via system openssl). Generate the key with
# `jericho backup-keygen`; keep a copy of the key SEPARATE from the mirror.
JERICHO_BACKUP_ENCRYPTION_KEY_FILE=
# Strict "Inbox before canonical": route heuristic auto-promotion through review
# instead of creating a Knowledge Object directly. Explicit saves still promote.
JERICHO_INGESTION_STRICT_REVIEW=0
# Max graph-traversal depth for relational queries (hard safety ceiling 4).
JERICHO_GRAPH_MAX_DEPTH=2

JERICHO_API_HOST=127.0.0.1
JERICHO_API_PORT=8000
JERICHO_API_TOKEN={api_token}
JERICHO_API_REQUIRE_TOKEN_ON_LOOPBACK=1
# Failed authentication attempts allowed per client IP per minute before 429.
JERICHO_API_AUTH_FAILURE_LIMIT_PER_MINUTE=10
JERICHO_CORS_ORIGINS=http://127.0.0.1:8000,http://localhost:8000

JERICHO_TELEGRAM_BRIDGE_SECRET={bridge_secret}
JERICHO_TELEGRAM_BOT_TOKEN=
# Deny-by-default: the bot ignores every chat until one of these is set.
JERICHO_TELEGRAM_ALLOWED_CHAT_IDS=
JERICHO_TELEGRAM_OWNER_CHAT_IDS=
JERICHO_TELEGRAM_SIGNATURE_MAX_AGE_SEC=90

JERICHO_WORKERS_ENABLED=1
# Reminders organ: proactive Telegram nudges for upcoming dated events.
JERICHO_REMINDERS_ENABLED=1
JERICHO_REMINDERS_LEAD_DAYS=1
JERICHO_REMINDERS_POLL_INTERVAL_SEC=900
# Reflection organ: weekly self-review digest (optional model synthesis).
JERICHO_REFLECTION_ENABLED=1
JERICHO_REFLECTION_INTERVAL_SEC=86400
JERICHO_REFLECTION_MIN_KNOWLEDGE=3
# Chronicle organ (temporal presence): "on this day" resurfacing push.
JERICHO_CHRONICLE_ENABLED=1
JERICHO_CHRONICLE_INTERVAL_SEC=86400
# Sentinel organ (self-monitoring): pushes health alerts (crashed workers,
# stale/missing backups, unreachable vLLM) to the owner via the outbound channel.
JERICHO_SENTINEL_ENABLED=1
JERICHO_SENTINEL_INTERVAL_SEC=3600
JERICHO_SENTINEL_CHECK_LLM=1
# Inject the derived user model (people/projects/interests) into chat context.
JERICHO_PROFILE_IN_CONTEXT=1
# Quiet hours (UTC) — no proactive organ enqueues messages in this window.
JERICHO_QUIET_HOURS_START=22
JERICHO_QUIET_HOURS_END=8
JERICHO_WEB_ALLOW_PRIVATE_NETWORKS=0
JERICHO_CODE_EXECUTION_ENABLED=0
JERICHO_MAX_UPLOAD_BYTES=52428800
JERICHO_MAX_ARCHIVE_ENTRIES=500
JERICHO_MAX_ARCHIVE_UNCOMPRESSED_BYTES=262144000
"""
    _write_private_text_atomic(target, content)
    print(f"Jericho инициализирован: {settings.home}")
    print(f"Конфигурация и новые секреты записаны в: {target}")
    print(f"Каталог модели: {settings.model_dir}")
    print("\nДальше:")
    print("  1. Положите веса модели в указанный каталог.")
    print("  2. Заполните JERICHO_TELEGRAM_BOT_TOKEN в .env.local (Telegram можно подключить позже).")
    print("  3. Запустите vLLM и затем всё остальное одной командой: `jericho up`.")
    print("  4. Проверьте установку: `jericho status --check-llm`.")
    print("  5. Для автозапуска: `jericho install-services` (systemd --user юниты).")
    print("  6. После первых данных создайте копию: `jericho backup --label first`.")
    return 0


def _status(args: argparse.Namespace) -> int:
    from jericho.config import load_settings
    from jericho.diagnostics import collect_diagnostics

    settings = load_settings()
    result = collect_diagnostics(settings, check_llm_port=args.check_llm)
    if args.json:
        _json_print({"version": __version__, **result})
    else:
        db = result["database"]
        backups = result.get("backups", {})
        workers = result.get("workers", {})
        lease = result.get("backend_lease", {})
        print(f"Jericho {__version__}")
        print(f"State: {result.get('state', 'unknown')}")
        print(f"Home: {settings.home}")
        print(f"Database: {settings.database_path}")
        print(f"Schema: {db.get('schema_version', 'not initialized')}")
        print(f"Database integrity: {db.get('integrity_check', 'not created')}")
        latest = backups.get("latest") or {}
        if backups.get("verified"):
            print(f"Latest backup: verified · {latest.get('database')} · {latest.get('created_at')}")
        else:
            print(f"Latest backup: {backups.get('state', 'unknown')}")
        backend_state = lease.get("state", "unknown")
        backend_pid = lease.get("pid")
        print(f"Backend lease: {backend_state}{f' · pid {backend_pid}' if backend_pid else ''}")
        from jericho.diagnostics.runtime_lease import inspect_process_lease

        bridge_lease = inspect_process_lease(
            settings.state_dir / "telegram-inbox.sqlite3.lock",
            protocol="jericho.telegram-bridge.v1",
        )
        bridge_pid = bridge_lease.get("pid")
        print(
            f"Bridge lease: {bridge_lease.get('state', 'unknown')}"
            f"{f' · pid {bridge_pid}' if bridge_pid else ''}"
        )
        outbound_pending = db.get("outbound_pending")
        if outbound_pending is not None:
            print(f"Outbound queue: {outbound_pending} pending")
        print(
            "Workers: "
            f"{workers.get('state', 'unknown')} · "
            f"tasks {workers.get('task_count', 0)} · "
            f"healthy {'yes' if workers.get('healthy', True) else 'no'}"
        )
        print(
            f"Model directory: {settings.model_dir} "
            f"({'weights detected' if result['paths']['model'].get('usable_files_detected') else 'empty or missing'})"
        )
        print(f"Configuration: {'OK' if result['ok'] else 'needs attention'}")
        for issue in result.get("configuration_issues", []):
            print(f"  - {issue}")
        if args.check_llm:
            endpoint = result.get("llm_endpoint", {})
            print(f"LLM endpoint: {'reachable' if endpoint.get('reachable') else 'unreachable'}")
        actions = result.get("actions", [])
        if actions:
            print("\nRecommended actions:")
            for action in actions:
                marker = {"error": "!", "warning": "~", "setup": "+"}.get(
                    str(action.get("severity")),
                    "-",
                )
                print(f"  {marker} {action.get('title')}: {action.get('detail')}")
                if action.get("command"):
                    print(f"      {action['command']}")
    return 0 if result.get("state") in {"ready", "attention"} else 1


def _doctor(args: argparse.Namespace) -> int:
    from jericho.config import ensure_runtime_dirs, load_settings
    from jericho.diagnostics import collect_diagnostics

    settings = load_settings()
    ensure_runtime_dirs(settings)
    result = collect_diagnostics(settings, check_llm_port=args.check_llm)
    _json_print(result)
    return 0 if result.get("state") in {"ready", "attention"} else 1


def _backup(args: argparse.Namespace) -> int:
    from jericho.backup_mirror import mirror_backups
    from jericho.config import ensure_runtime_dirs, load_settings
    from jericho.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        result = storage.create_backup(label=args.label)
    finally:
        storage.close()
    mirror = mirror_backups(settings)
    _json_print({**result, "mirror": mirror})
    if not mirror.get("enabled"):
        print(
            "⚠ Зеркалирование выключено: копия лежит на том же диске. "
            "Настройте JERICHO_BACKUP_MIRROR_DIR (внешний диск/синхронизируемый каталог).",
            file=sys.stderr,
        )
    return 0


def _backup_keygen(args: argparse.Namespace) -> int:
    """Generate a backup-encryption key file (referenced by the env setting)."""
    from jericho.config import load_settings

    settings = load_settings()
    target = Path(args.out).expanduser() if args.out else settings.backup_encryption_key_file
    if target is None:
        print(
            "Укажите --out или задайте JERICHO_BACKUP_ENCRYPTION_KEY_FILE в .env.local",
            file=sys.stderr,
        )
        return 2
    if target.exists() and not args.force:
        print(f"Не перезаписываю существующий ключ: {target} (используйте --force)")
        return 2
    _write_private_text_atomic(target, secrets.token_hex(32) + "\n")
    print(f"Ключ шифрования бэкапов записан: {target} (права 600)")
    print("Храните копию ключа ОТДЕЛЬНО от зеркала: без ключа .enc-копии невосстановимы.")
    return 0


def _decrypt_backup(args: argparse.Namespace) -> int:
    from jericho.backup_mirror import decrypt_file
    from jericho.config import load_settings

    settings = load_settings()
    key_file = Path(args.key).expanduser() if args.key else settings.backup_encryption_key_file
    if key_file is None:
        print("Укажите --key или задайте JERICHO_BACKUP_ENCRYPTION_KEY_FILE", file=sys.stderr)
        return 2
    source = Path(args.filename).expanduser()
    destination = (
        Path(args.out).expanduser() if args.out else source.with_name(source.name.removesuffix(".enc"))
    )
    if destination.exists():
        print(f"Не перезаписываю существующий файл: {destination}", file=sys.stderr)
        return 2
    decrypt_file(source, destination, key_file)
    print(f"Расшифровано: {destination}")
    print("Дальше: `jericho verify-backup` рядом с манифестом или `jericho restore-backup`.")
    return 0


def _verify_backup(args: argparse.Namespace) -> int:
    from jericho.config import ensure_runtime_dirs, load_settings
    from jericho.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        filename = args.filename
        if not filename:
            backups = storage.list_backups()
            if not backups:
                print("Резервных копий не найдено.", file=sys.stderr)
                return 2
            filename = str(backups[0]["database"])
        result = storage.verify_backup(filename)
    finally:
        storage.close()
    _json_print(result)
    return 0 if result.get("ok") else 1


def _restore_backup(args: argparse.Namespace) -> int:
    """Restore one database backup while the backend process role is exclusive."""

    if not args.yes:
        print(
            "Восстановление заменит активную SQLite-базу. Повторите команду с --yes после "
            "остановки backend и Telegram bridge.",
            file=sys.stderr,
        )
        return 2

    from jericho.config import ensure_runtime_dirs, load_settings
    from jericho.diagnostics.runtime_lease import ProcessLease
    from jericho.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    with ProcessLease(settings.state_dir / "backend.lock", protocol="jericho.backend.v1"):
        storage = init_storage(settings)
        try:
            filename = args.filename
            if not filename:
                backups = storage.list_backups()
                if not backups:
                    print("Резервных копий не найдено.", file=sys.stderr)
                    return 2
                filename = str(backups[0]["database"])
            result = storage.restore_backup(
                filename,
                safety_label=f"pre-restore-{Path(filename).stem}",
            )
        finally:
            storage.close()
    _json_print(result)
    print(
        "Важно: восстановлена только SQLite-база; raw files, memory vault, веса модели и "
        "локальная конфигурация не изменялись.",
        file=sys.stderr,
    )
    return 0


def _export_user(args: argparse.Namespace) -> int:
    from jericho.config import ensure_runtime_dirs, load_settings
    from jericho.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        result = storage.export_user(args.user_id)
    finally:
        storage.close()
    _json_print(result)
    return 0


def _purge(args: argparse.Namespace) -> int:
    """Irreversibly hard-delete soft-deleted knowledge while the backend is stopped."""

    if not args.yes:
        print(
            "Purge необратимо уничтожает объекты, версии, raw-файлы, vault-копии и graph-links. "
            "Повторите с --yes после остановки backend и Telegram bridge.",
            file=sys.stderr,
        )
        return 2

    from jericho.config import ensure_runtime_dirs, load_settings
    from jericho.diagnostics.runtime_lease import ProcessLease
    from jericho.memory import MemoryVault
    from jericho.permissions import LEGACY_OWNER_USER_ID
    from jericho.purge import purge_knowledge
    from jericho.storage import init_storage
    from jericho.storage.models import AuditEntry, new_id

    settings = load_settings()
    ensure_runtime_dirs(settings)
    with ProcessLease(settings.state_dir / "backend.lock", protocol="jericho.backend.v1"):
        storage = init_storage(settings)
        try:
            vault = MemoryVault(settings.memory_vault_dir)
            if args.id:
                owner = args.user or LEGACY_OWNER_USER_ID
                try:
                    report = purge_knowledge(storage, settings, vault, args.id, owner)
                except ValueError as exc:
                    print(str(exc), file=sys.stderr)
                    return 2
                if not report.get("existed"):
                    print("Объект не найден.", file=sys.stderr)
                    return 2
                results = [report]
            else:
                days = (
                    args.older_than_days
                    if args.older_than_days is not None
                    else settings.purge_retention_days
                )
                candidates = storage.list_purgeable_knowledge(
                    args.user, older_than_days=days, limit=args.limit
                )
                results = [
                    purge_knowledge(storage, settings, vault, cand["id"], cand["user_id"])
                    for cand in candidates
                ]
            for report in results:
                storage.log_audit(
                    AuditEntry(
                        id=new_id("audit"),
                        user_id=str(report.get("user_id") or ""),
                        action="cli.knowledge.purge",
                        target_type="knowledge_object",
                        target_id=str(report.get("knowledge_object_id") or ""),
                        before_json=None,
                        after_json=report,
                        ip_address="",
                        request_id="cli",
                    )
                )
        finally:
            storage.close()
    _json_print({"purged": len(results), "items": results})
    return 0


def _mint_token(args: argparse.Namespace) -> int:
    """Issue a scoped API token bound to an account/preset (bootstrap path)."""

    import hashlib
    import secrets

    from jericho.config import ensure_runtime_dirs, load_settings
    from jericho.permissions import BUILTIN_PRESET_KEYS
    from jericho.storage import init_storage, validate_user_id

    preset = args.preset
    if preset and preset not in BUILTIN_PRESET_KEYS:
        print(
            f"Неизвестный preset: {preset}. Допустимо: {', '.join(sorted(BUILTIN_PRESET_KEYS))}.",
            file=sys.stderr,
        )
        return 2

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        try:
            user_id = validate_user_id(args.user)
        except ValueError as exc:
            print(str(exc), file=sys.stderr)
            return 2
        storage.ensure_user(
            user_id,
            source="api-token",
            display_name=args.user,
            preset_key=preset or "user",
        )
        # ensure_user never changes an existing account's preset; apply it explicitly.
        if preset:
            storage.update_user(user_id, preset_key=preset)
        current = storage.get_user(user_id) or {}
        secret = "jrc_" + secrets.token_urlsafe(32)
        token_hash = hashlib.sha256(secret.encode("utf-8")).hexdigest()
        record = storage.create_api_token(user_id, token_hash, label=args.label or "", created_by="cli")
    finally:
        storage.close()
    _json_print(
        {
            "id": record.get("id"),
            "user_id": user_id,
            "preset": current.get("preset_key"),
            "label": args.label or "",
        }
    )
    print(f"API-токен (показывается один раз): {secret}", file=sys.stderr)
    return 0


def _revoke_token(args: argparse.Namespace) -> int:
    from jericho.config import ensure_runtime_dirs, load_settings
    from jericho.storage import init_storage

    settings = load_settings()
    ensure_runtime_dirs(settings)
    storage = init_storage(settings)
    try:
        revoked = storage.revoke_api_token(args.token_id)
    finally:
        storage.close()
    if not revoked:
        print("Токен не найден или уже отозван.", file=sys.stderr)
        return 2
    _json_print({"status": "revoked", "id": args.token_id})
    return 0


def _run_telegram_bridge() -> int:
    from jericho.config import ensure_runtime_dirs, load_settings, validate_settings
    from jericho.telegram_bridge import TelegramBridge, TelegramConfig

    settings = load_settings()
    ensure_runtime_dirs(settings)
    # Surface deny-by-default and credential problems as a clear CLI error before
    # the bridge starts, since validate_settings is otherwise only run by the
    # backend process.
    problems = validate_settings(settings, production=not settings.is_loopback_bind)
    fatal = [item for item in problems if not item.startswith("warning:")]
    if fatal:
        raise ValueError("Invalid Jericho configuration: " + "; ".join(fatal))
    token = os.environ.get("JERICHO_TELEGRAM_BOT_TOKEN", "").strip()
    # This compares configured bind literals; it does not open a listener.
    host = (
        "127.0.0.1"  # nosec B104
        if settings.api_host in {"0.0.0.0", "::", "localhost"}  # nosec B104
        else settings.api_host
    )
    config = TelegramConfig(
        bot_token=token,
        backend_url=os.environ.get(
            "JERICHO_BACKEND_URL",
            f"http://{host}:{settings.api_port}",
        ).rstrip("/"),
        bridge_secret=settings.telegram_bridge_secret,
        allowed_chat_ids=settings.telegram_effective_allowed_chat_ids,
        inbox_db_path=str(settings.state_dir / "telegram-inbox.sqlite3"),
        max_document_bytes=settings.max_upload_bytes,
        backend_timeout_sec=max(30.0, settings.llm_timeout_sec + 30.0),
        # Outbound delivery polls faster than the reminder scan so a queued
        # message reaches the user promptly rather than on the next scan.
    )
    bridge = TelegramBridge(config)
    try:
        asyncio.run(bridge.run())
    except KeyboardInterrupt:
        print("\nTelegram bridge остановлен.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="jericho",
        description="Local-first personal Knowledge Operating System",
    )
    parser.add_argument("--version", action="version", version=f"Jericho {__version__}")
    parser.add_argument("--log-level", default=os.environ.get("JERICHO_LOG_LEVEL", "INFO"))
    parser.add_argument(
        "--env-file",
        help="Load configuration from this .env file (default: ./.env.local)",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    init = sub.add_parser("init", help="Create runtime directories and a private .env.local")
    init.add_argument("--home", help="Override JERICHO_HOME for the generated configuration")
    init.add_argument("--force", action="store_true", help="Replace an existing environment file")
    init.set_defaults(handler=_init_environment)

    server = sub.add_parser("server", help="Start the API and Admin UI")
    server.set_defaults(handler=lambda _: _run_server())

    telegram = sub.add_parser("telegram-bridge", help="Start durable Telegram long polling")
    telegram.set_defaults(handler=lambda _: _run_telegram_bridge())

    up = sub.add_parser("up", help="Validate config, then run backend (+bridge) under supervision")
    up.add_argument("--no-bridge", action="store_true", help="Do not start the Telegram bridge")
    up.set_defaults(handler=_up)

    services = sub.add_parser("install-services", help="Generate systemd --user units for backend and bridge")
    services.add_argument("--dir", help="Target directory (default: ~/.config/systemd/user)")
    services.set_defaults(handler=_install_services)

    status = sub.add_parser("status", help="Show concise local status")
    status.add_argument("--json", action="store_true")
    status.add_argument("--check-llm", action="store_true")
    status.set_defaults(handler=_status)

    doctor = sub.add_parser("doctor", help="Run detailed diagnostics")
    doctor.add_argument("--check-llm", action="store_true")
    doctor.set_defaults(handler=_doctor)

    backup = sub.add_parser("backup", help="Create and integrity-check an online SQLite backup")
    backup.add_argument("--label", default="cli")
    backup.set_defaults(handler=_backup)

    keygen = sub.add_parser("backup-keygen", help="Generate the backup-encryption key file")
    keygen.add_argument("--out", help="Key file path (default: JERICHO_BACKUP_ENCRYPTION_KEY_FILE)")
    keygen.add_argument("--force", action="store_true", help="Replace an existing key file")
    keygen.set_defaults(handler=_backup_keygen)

    decrypt = sub.add_parser("decrypt-backup", help="Decrypt an .enc mirror copy for restore")
    decrypt.add_argument("filename", help="Encrypted backup file (…sqlite3.enc)")
    decrypt.add_argument("--out", help="Output path (default: strip .enc)")
    decrypt.add_argument("--key", help="Key file (default: JERICHO_BACKUP_ENCRYPTION_KEY_FILE)")
    decrypt.set_defaults(handler=_decrypt_backup)

    verify = sub.add_parser("verify-backup", help="Verify one backup (or the newest one)")
    verify.add_argument("filename", nargs="?")
    verify.set_defaults(handler=_verify_backup)

    restore = sub.add_parser(
        "restore-backup",
        help="Atomically restore a verified SQLite backup while Jericho is stopped",
    )
    restore.add_argument("filename", nargs="?", help="Backup filename (default: newest manifest)")
    restore.add_argument(
        "--yes",
        action="store_true",
        help="Confirm replacement of the active database and creation of a safety backup",
    )
    restore.set_defaults(handler=_restore_backup)

    export = sub.add_parser("export-user", help="Export one tenant's data as JSON")
    export.add_argument("user_id")
    export.set_defaults(handler=_export_user)

    purge = sub.add_parser(
        "purge",
        help="Hard-delete soft-deleted knowledge (rows, versions, FTS, raw file, vault) while stopped",
    )
    purge.add_argument("--id", help="Purge one specific knowledge object id (must be soft-deleted)")
    purge.add_argument("--user", help="Restrict to one tenant (default: all tenants for batch)")
    purge.add_argument(
        "--older-than-days",
        type=int,
        default=None,
        help="Retention window; only purge objects soft-deleted at least this long ago",
    )
    purge.add_argument("--limit", type=int, default=200, help="Maximum objects to purge in one run")
    purge.add_argument("--yes", action="store_true", help="Confirm irreversible destruction")
    purge.set_defaults(handler=_purge)

    mint = sub.add_parser("mint-token", help="Issue a scoped API token for an account/preset")
    mint.add_argument("--user", required=True, help="Account id the token authenticates as")
    mint.add_argument("--preset", help="Set the account preset (owner/admin/moderator/user/guest)")
    mint.add_argument("--label", help="Human-readable label for the token")
    mint.set_defaults(handler=_mint_token)

    revoke = sub.add_parser("revoke-token", help="Revoke a previously issued API token by id")
    revoke.add_argument("token_id")
    revoke.set_defaults(handler=_revoke_token)
    return parser


def _run_server() -> int:
    from jericho.server import run_server

    run_server()
    return 0


def _up(args: argparse.Namespace) -> int:
    """One-command launch: validate config, then supervise backend (+bridge)."""
    import sys

    from jericho.config import ensure_runtime_dirs, load_settings, validate_settings
    from jericho.diagnostics.runtime_lease import inspect_process_lease
    from jericho.supervisor import ChildSpec, Supervisor

    settings = load_settings()
    ensure_runtime_dirs(settings)
    problems = validate_settings(settings, production=not settings.is_loopback_bind)
    errors = [item for item in problems if not item.startswith("warning:")]
    for problem in problems:
        print(("⚠ " if problem.startswith("warning:") else "✖ ") + problem)
    if errors:
        print("Конфигурация не готова — исправьте ошибки выше (.env.local).")
        return 2

    backend_lease = inspect_process_lease(settings.state_dir / "backend.lock", protocol="jericho.backend.v1")
    if backend_lease.get("active"):
        print(f"Backend уже запущен (pid {backend_lease.get('pid')}). Второй не нужен.")
        return 2

    env_file = os.environ.get("JERICHO_ENV_FILE", "")
    base_argv = [sys.executable, "-m", "jericho.cli"]
    if env_file:
        base_argv += ["--env-file", env_file]

    children = [
        ChildSpec(
            name="backend",
            argv=[*base_argv, "server"],
            log_path=settings.log_dir / "backend.log",
            cwd=settings.home,
        )
    ]
    bot_token = os.environ.get("JERICHO_TELEGRAM_BOT_TOKEN", "").strip()
    if args.no_bridge:
        print("Мост Telegram пропущен (--no-bridge).")
    elif not bot_token:
        print("Мост Telegram пропущен: JERICHO_TELEGRAM_BOT_TOKEN не задан.")
    else:
        children.append(
            ChildSpec(
                name="telegram-bridge",
                argv=[*base_argv, "telegram-bridge"],
                log_path=settings.log_dir / "telegram-bridge.log",
                cwd=settings.home,
            )
        )

    print(f"Запускаю {', '.join(child.name for child in children)}; логи в {settings.log_dir}")
    print("Остановка: Ctrl+C (дети получают SIGTERM и завершаются штатно).")
    return Supervisor(children).run()


_SYSTEMD_UNIT_TEMPLATE = """[Unit]
Description=Jericho {role}
After=network-online.target{after_extra}

[Service]
Type=simple
ExecStart={exec_start}
Restart=on-failure
RestartSec=5
{environment}WorkingDirectory={workdir}

[Install]
WantedBy=default.target
"""


def _install_services(args: argparse.Namespace) -> int:
    """Generate systemd --user units; printing, not enabling — the user decides."""
    import sys

    from jericho.config import load_settings

    settings = load_settings()
    target_dir = Path(args.dir or Path.home() / ".config" / "systemd" / "user").expanduser()
    target_dir.mkdir(parents=True, exist_ok=True)

    env_file = os.environ.get("JERICHO_ENV_FILE", "")
    env_arg = f" --env-file {env_file}" if env_file else ""
    environment = f"Environment=JERICHO_HOME={settings.home}\n"

    units: list[tuple[str, str]] = []
    units.append(
        (
            "jericho-backend.service",
            _SYSTEMD_UNIT_TEMPLATE.format(
                role="backend (API + Admin UI)",
                after_extra="",
                exec_start=f"{sys.executable} -m jericho.cli{env_arg} server",
                environment=environment,
                workdir=settings.home,
            ),
        )
    )
    units.append(
        (
            "jericho-bridge.service",
            _SYSTEMD_UNIT_TEMPLATE.format(
                role="Telegram bridge",
                after_extra=" jericho-backend.service",
                exec_start=f"{sys.executable} -m jericho.cli{env_arg} telegram-bridge",
                environment=environment,
                workdir=settings.home,
            ),
        )
    )
    for name, content in units:
        (target_dir / name).write_text(content, encoding="utf-8")
        print(f"Записан {target_dir / name}")
    if sys.executable.startswith(("/tmp/", "/var/tmp/")):
        print(
            "⚠ ExecStart указывает на временный Python-интерпретатор. Установите Jericho в "
            "постоянный venv и перегенерируйте юниты перед enable."
        )
    print()
    print("Дальше (мост включайте только с настроенным JERICHO_TELEGRAM_BOT_TOKEN):")
    print("  systemctl --user daemon-reload")
    print("  systemctl --user enable --now jericho-backend")
    print("  systemctl --user enable --now jericho-bridge")
    print("  loginctl enable-linger $USER   # чтобы сервисы жили без активной сессии")
    return 0


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    if args.env_file:
        os.environ["JERICHO_ENV_FILE"] = str(Path(args.env_file).expanduser().resolve())
    # Load local secrets before installing formatters, otherwise early startup
    # failures could render credential-bearing values without exact redaction.
    from jericho.config import load_local_env_file

    load_local_env_file()
    configure_logging(args.log_level)
    try:
        code = int(args.handler(args) or 0)
    except (ValueError, RuntimeError, FileNotFoundError) as exc:
        logging.getLogger(__name__).error("%s", exc)
        code = 2
    raise SystemExit(code)


if __name__ == "__main__":
    main()
