"""Ingestion: the Inbox: classification, promotion and return.

Moved verbatim out of the single 3564-line module: same names, signatures and
bodies. Mixed back into ``IngestionPipeline``, so every collaborator resolves
exactly as before and no call site moved.
"""

from __future__ import annotations

from friday.ingestion._base import (
    DECLARED_ENTITY_METHODS,
    LOGGER,
    Any,
    EntityType,
    FeedbackItem,
    FeedbackType,
    InboxItem,
    InboxStatus,
    KnowledgeEnrichment,
    KnowledgeObject,
    PipelineShared,
    PromotionAssessment,
    RawObject,
    _clamp,
    _json_dict,
    _json_list,
    new_id,
    utc_now,
)


class ReviewMixin(PipelineShared):
    def list_inbox(self, user_id: str, status: InboxStatus | None = None) -> list[dict[str, Any]]:
        return self.storage.list_inbox_detailed(user_id, status)

    def _revive_reviewed_ko(
        self,
        inbox_id: str,
        user_id: str,
        item: dict[str, Any],
        reviewer: str,
    ) -> str | None:
        """Bring back the object this row already had, instead of minting a second one.

        Two paths clear `knowledge_object_id` and soft-delete the object while leaving
        the row promotable again: «Игнорировать», and «Вернуть в Inbox» from the safe
        revision screen — which the UI presents as reversible. Promoting afterwards
        rebuilt everything from the raw text, so the reviewer's own title, summary and
        tags were replaced by autogenerated ones and the object's versions, entity
        links, usage history and embeddings stayed stranded on an id nothing lists.

        Both paths leave the id on the row, so this reads it rather than guessing.
        Returns None when there is nothing to revive, and the caller creates as before.
        """
        suggestions = _json_dict(item.get("suggestions_json"))
        candidate = str(
            suggestions.get("ignored_knowledge_object_id")
            or _json_dict(suggestions.get("legacy_cleanup")).get("source_knowledge_object_id")
            or ""
        )
        if not candidate:
            return None
        previous = self.storage.get_knowledge_object(candidate, user_id)
        if not previous or not previous.get("deleted_at"):
            # Already live, or gone for good: creating is the honest fallback.
            return None
        if str(previous.get("raw_object_id") or "") != str(item.get("raw_object_id") or ""):
            return None

        metadata = _json_dict(previous.get("metadata_json"))
        # The ignore verdict becomes history rather than a current label — a live
        # object carrying `ignored_from_inbox` would make its own provenance lie.
        history = [entry for entry in _json_list(metadata.get("review_history")) if isinstance(entry, str)]
        if metadata.get("ignored_from_inbox"):
            history.append(f"ignored by {metadata.get('ignored_by') or 'unknown'} from {inbox_id}")
        metadata.pop("ignored_from_inbox", None)
        metadata.pop("ignored_by", None)
        metadata["review_history"] = history[-20:]
        metadata["restored_from_inbox"] = inbox_id
        metadata["restored_by"] = reviewer

        self.storage.update_knowledge_fields(
            candidate,
            user_id,
            deleted_at=None,
            lifecycle_stage="active",
            metadata_json=metadata,
        )
        if not self.storage.claim_inbox_promotion(inbox_id, user_id, candidate):
            return (self.storage.get_inbox_item(inbox_id, user_id) or {}).get("knowledge_object_id")
        return candidate

    def _create_promoted_ko(
        self,
        inbox_id: str,
        user_id: str,
        item: dict[str, Any],
        reviewer: str,
        *,
        title: str | None,
        summary: str | None,
        knowledge_kind: str | None,
        importance: float | None,
        metadata: dict[str, Any] | None,
        tags: list[str] | None,
    ) -> str | None:
        """Build the canonical KO for a promoted Inbox item and claim the slot.

        Returns the resulting knowledge_object_id. The caller holds the promotion
        lock, so the claim normally wins; the loser branch stays as defence in
        depth and SOFT-deletes its orphan (never hard-purge — purge can cascade to
        the Raw Object shared with the winner's KO).
        """
        raw = self.storage.get_raw_object(item["raw_object_id"], user_id)
        if not raw:
            raise ValueError("Inbox Raw Object not found")
        suggestions = _json_dict(item.get("suggestions_json"))
        raw_content = str(raw.get("raw_content") or "")
        assessment = self.assess_text(raw_content, force_knowledge=True)
        enrichment = self._enrich(raw_content, assessment, user_id=user_id)
        suggested_metadata_value = suggestions.get("metadata")
        suggested_metadata: dict[str, Any] = (
            suggested_metadata_value if isinstance(suggested_metadata_value, dict) else {}
        )
        ko = KnowledgeObject(
            id=new_id("ko"),
            user_id=user_id,
            raw_object_id=raw["id"],
            content=raw_content,
            content_type=str(raw.get("content_type") or "text"),
            title=(title or suggestions.get("title") or enrichment.title)[:200],
            summary=(summary or suggestions.get("summary") or enrichment.summary)[:2000],
            tags_json=sorted(set(tags if tags is not None else suggestions.get("tags") or enrichment.tags))[
                :32
            ],
            metadata_json={
                **enrichment.metadata,
                # Дата документа взята из провенанса файла при приёме и живёт в
                # метаданных raw. Обогащение считается заново по тексту и о ней не
                # знает, поэтому при продвижении её надо перенести явно — иначе у
                # продвинутого из Inbox документа даты не будет вовсе.
                **(
                    {"document_date": str(_json_dict(raw.get("metadata_json")).get("document_date"))}
                    if _json_dict(raw.get("metadata_json")).get("document_date")
                    else {}
                ),
                **suggested_metadata,
                **(metadata or {}),
                "manually_promoted_from_inbox": inbox_id,
                "reviewed_by": reviewer,
            },
            knowledge_kind=str(
                knowledge_kind or suggestions.get("knowledge_kind") or enrichment.knowledge_kind
            )[:40],
            importance=_clamp(
                importance
                if importance is not None
                else float(suggestions.get("importance", enrichment.importance))
            ),
            quality_score=max(
                0.55,
                _clamp(float(suggestions.get("quality_score", enrichment.quality_score))),
            ),
            promotion_score=1.0,
        )
        self.storage.store_knowledge_object(ko)
        if self.storage.claim_inbox_promotion(inbox_id, user_id, ko.id):
            deferred_links, _ = self._link_entities(
                user_id,
                ko.id,
                raw["id"],
                suggestions.get("entities") or enrichment.entities,
            )
            if self.knowledge_graph:
                # Parity with _promote_raw: confirmation-time promotion records
                # event dates and proposes graph evolution the same way.
                self._record_event_times(user_id, raw_content, deferred_links)
                self.knowledge_graph.suggest_relations_for_knowledge(user_id, ko.id)
                self.knowledge_graph.detect_conflicts_for_knowledge(user_id, ko.id)
            return ko.id
        self.storage.soft_delete_knowledge_object(ko.id, user_id)
        refreshed = self.storage.get_inbox_item(inbox_id, user_id)
        return (refreshed or {}).get("knowledge_object_id")

    def classify_inbox_item(
        self,
        user_id: str,
        inbox_id: str,
        status: InboxStatus,
        *,
        entity_id: str | None = None,
        tags: list[str] | None = None,
        notes: str = "",
        reviewed_by: str | None = None,
        promote: bool | None = None,
        title: str | None = None,
        summary: str | None = None,
        knowledge_kind: str | None = None,
        importance: float | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any] | None:
        item = self.storage.get_inbox_item(inbox_id, user_id)
        if not item:
            return None
        reviewer = reviewed_by or user_id
        if entity_id:
            entity = self.storage.get_entity(entity_id, user_id)
            if not entity or entity.get("deleted_at"):
                raise ValueError("Entity not found for user")

        ko_id = item.get("knowledge_object_id")
        should_promote = promote is True or (promote is None and status == InboxStatus.CLASSIFIED)
        if not ko_id and should_promote:
            with self._promotion_lock:
                # Serialised within this (single) backend process so concurrent
                # approvals cannot race on the shared storage connection. Re-read
                # inside the lock: only the first holder creates the KO; the rest
                # observe its id and adopt it.
                ko_id = (self.storage.get_inbox_item(inbox_id, user_id) or item).get("knowledge_object_id")
                if not ko_id:
                    ko_id = self._revive_reviewed_ko(inbox_id, user_id, item, reviewer)
                if not ko_id:
                    ko_id = self._create_promoted_ko(
                        inbox_id,
                        user_id,
                        item,
                        reviewer,
                        title=title,
                        summary=summary,
                        knowledge_kind=knowledge_kind,
                        importance=importance,
                        metadata=metadata,
                        tags=tags,
                    )

        if ko_id:
            updates: dict[str, Any] = {}
            if tags is not None:
                updates["tags_json"] = tags
            if title is not None:
                updates["title"] = title[:200]
            if summary is not None:
                updates["summary"] = summary[:2000]
            if knowledge_kind is not None:
                updates["knowledge_kind"] = knowledge_kind[:40]
            if importance is not None:
                updates["importance"] = _clamp(importance)
            if metadata is not None:
                current = self.storage.get_knowledge_object(ko_id, user_id) or {}
                updates["metadata_json"] = {**_json_dict(current.get("metadata_json")), **metadata}
            if updates:
                self.storage.update_knowledge_fields(ko_id, user_id, **updates)

        if entity_id and ko_id and self.knowledge_graph:
            self.knowledge_graph.link_knowledge_to_entity(
                ko_id,
                entity_id,
                user_id,
                confidence=1.0,
                evidence={"reviewed_from_inbox": inbox_id},
                reviewed_by=reviewer,
            )

        # "Ignore" is a verdict that the material must not be knowledge: a KO
        # attached to the item (legacy pre-review promotion, auto-classified
        # text) is soft-deleted so it leaves retrieval, with provenance of the
        # decision on the object. Raw Object and version history survive.
        ignored_ko_id: str | None = None
        if ko_id and status == InboxStatus.IGNORED:
            current_ko = self.storage.get_knowledge_object(ko_id, user_id)
            if current_ko and not current_ko.get("deleted_at"):
                self.storage.update_knowledge_fields(
                    ko_id,
                    user_id,
                    metadata_json={
                        **_json_dict(current_ko.get("metadata_json")),
                        "ignored_from_inbox": inbox_id,
                        "ignored_by": reviewer,
                    },
                )
                self.storage.soft_delete_knowledge_object(ko_id, user_id)
            ignored_ko_id = ko_id
            ko_id = None
            # A breadcrumb on the row itself. Ignoring clears `knowledge_object_id`, so
            # without it the address of the object a human already curated is gone: a
            # later promotion of the same row rebuilt everything from the raw text and
            # minted a NEW id, leaving the reviewer's title, summary and tags
            # unreachable and the old object's versions, entity links, usage history
            # and embeddings stranded on a row nothing lists.
            #
            # Deliberately NOT found by scanning for `manually_promoted_from_inbox`:
            # the losing branch of a promotion race soft-deletes its own orphan
            # carrying that same marker, and reviving THAT would put two live objects
            # on one Raw Object.
            suggestions = {
                **_json_dict(item.get("suggestions_json")),
                "ignored_knowledge_object_id": ignored_ko_id,
            }

        self.storage.update_inbox_status(
            inbox_id,
            status,
            reviewer,
            user_id=user_id,
            suggestions=suggestions if ignored_ko_id else None,
            suggested_entity_id=entity_id,
            suggested_tags=tags,
            knowledge_object_id=ko_id if ko_id else None,
            clear_knowledge_object_id=ignored_ko_id is not None,
            suggested_action="classified" if ko_id else status.value,
            promotion_score=1.0 if ko_id else None,
            notes=notes if notes else None,
        )
        raw = self.storage.get_raw_object(str(item["raw_object_id"]), user_id)
        raw_metadata = _json_dict(raw.get("metadata_json")) if raw else {}
        original_assessment = _json_dict(raw_metadata.get("promotion_assessment"))
        score = (
            1.0
            if ko_id and status == InboxStatus.CLASSIFIED
            else (-1.0 if status == InboxStatus.IGNORED else -0.5 if status == InboxStatus.ARCHIVED else 0.0)
        )
        if score:
            self.storage.store_feedback(
                FeedbackItem(
                    id=new_id("feedback"),
                    user_id=user_id,
                    target_type="classification",
                    target_id=str(item["raw_object_id"]),
                    feedback_type=FeedbackType.CLASSIFICATION,
                    score=score,
                    comment=notes[:1000],
                    context_json={
                        "inbox_id": inbox_id,
                        "status": status.value,
                        "knowledge_object_id": ko_id,
                        "knowledge_kind": str(
                            original_assessment.get("knowledge_kind")
                            or _json_dict(item.get("suggestions_json")).get("knowledge_kind")
                            or "note"
                        ),
                        "signals": original_assessment.get("signals", []),
                        "reviewed_by": reviewer,
                    },
                )
            )
        return self.storage.get_inbox_item(inbox_id, user_id)

    def return_knowledge_to_inbox(
        self,
        user_id: str,
        knowledge_object_id: str,
        *,
        reviewed_by: str,
        reason: str = "legacy quality review",
    ) -> dict[str, Any]:
        """Remove a questionable object from retrieval and reopen its Raw Object for review.

        This is intentionally reversible at the storage level: the Knowledge Object is soft
        deleted with a version snapshot, while the immutable Raw Object and all provenance remain.
        """

        current = self.storage.get_knowledge_object(knowledge_object_id, user_id)
        if not current or current.get("deleted_at"):
            raise ValueError("Knowledge Object not found")
        raw = self.storage.get_raw_object(str(current["raw_object_id"]), user_id)
        if not raw:
            raise ValueError("Knowledge Object has no accessible Raw Object")

        assessment = self.assess_text(str(raw.get("raw_content") or current.get("content") or ""))
        enrichment = self._enrich(
            str(raw.get("raw_content") or current.get("content") or ""),
            assessment,
            user_id=user_id,
        )
        metadata = _json_dict(current.get("metadata_json"))
        history = metadata.get("legacy_cleanup_history")
        if not isinstance(history, list):
            history = []
        history.append(
            {
                "action": "return_to_inbox",
                "reviewed_by": reviewed_by,
                "reason": reason,
                "at": utc_now(),
                "assessment": assessment.to_dict(),
            }
        )
        metadata["legacy_cleanup"] = {
            "reviewed": True,
            "action": "return_to_inbox",
            "reviewed_by": reviewed_by,
            "reason": reason,
        }
        metadata["legacy_cleanup_history"] = history[-20:]
        self.storage.update_knowledge_fields(
            knowledge_object_id,
            user_id,
            metadata_json=metadata,
            quality_score=min(float(current.get("quality_score", 0.5) or 0.5), enrichment.quality_score),
            promotion_score=min(
                float(current.get("promotion_score", 0.5) or 0.5), assessment.promotion_score
            ),
        )
        if not self.storage.soft_delete_knowledge_object(knowledge_object_id, user_id):
            raise ValueError("Knowledge Object could not be soft deleted")

        suggestions = enrichment.to_suggestions()
        suggestions["legacy_cleanup"] = {
            "source_knowledge_object_id": knowledge_object_id,
            "reason": reason,
            "assessment": assessment.to_dict(),
        }
        inbox = self.storage.find_inbox_by_raw(str(raw["id"]), user_id)
        if inbox:
            self.storage.update_inbox_status(
                str(inbox["id"]),
                InboxStatus.PENDING,
                reviewed_by,
                user_id=user_id,
                suggestions=suggestions,
                suggested_tags=enrichment.tags,
                suggested_action="legacy_review",
                clear_knowledge_object_id=True,
                promotion_score=assessment.promotion_score,
                quality_score=enrichment.quality_score,
                notes=reason,
            )
            inbox_id = str(inbox["id"])
        else:
            created = InboxItem(
                id=new_id("inbox"),
                user_id=user_id,
                raw_object_id=str(raw["id"]),
                knowledge_object_id=None,
                status=InboxStatus.PENDING,
                suggested_tags_json=enrichment.tags,
                suggestions_json=suggestions,
                suggested_action="legacy_review",
                promotion_score=assessment.promotion_score,
                quality_score=enrichment.quality_score,
                classification_notes=reason,
            )
            self.storage.store_inbox_item(created)
            inbox_id = created.id
        return {
            "knowledge_object_id": knowledge_object_id,
            "raw_object_id": raw["id"],
            "inbox_id": inbox_id,
            "status": "returned_to_inbox",
            "assessment": assessment.to_dict(),
        }

    def _store_review_inbox(
        self,
        raw: RawObject,
        assessment: PromotionAssessment,
        enrichment: KnowledgeEnrichment,
    ) -> InboxItem:
        inbox = InboxItem(
            id=new_id("inbox"),
            user_id=raw.user_id,
            raw_object_id=raw.id,
            knowledge_object_id=None,
            status=InboxStatus.PENDING,
            suggested_tags_json=enrichment.tags,
            suggestions_json=enrichment.to_suggestions(),
            suggested_action="promote" if assessment.promotion_score >= 0.5 else "review",
            promotion_score=assessment.promotion_score,
            quality_score=enrichment.quality_score,
            classification_notes=(
                f"action={assessment.action}; category={assessment.category}; "
                f"promotion={assessment.promotion_score:.2f}; quality={enrichment.quality_score:.2f}; "
                f"reason={assessment.reason}"
            ),
        )
        self.storage.store_inbox_item(inbox)
        return inbox

    def _promote_raw(
        self,
        *,
        raw: RawObject,
        content: str,
        assessment: PromotionAssessment,
        enrichment: KnowledgeEnrichment,
        force_pending: bool = False,
    ) -> dict[str, Any]:
        ko = KnowledgeObject(
            id=new_id("ko"),
            user_id=raw.user_id,
            raw_object_id=raw.id,
            content=content,
            content_type=raw.content_type,
            title=enrichment.title,
            summary=enrichment.summary,
            tags_json=enrichment.tags,
            metadata_json=enrichment.metadata,
            knowledge_kind=enrichment.knowledge_kind,
            importance=enrichment.importance,
            quality_score=enrichment.quality_score,
            promotion_score=assessment.promotion_score,
        )
        self.storage.store_knowledge_object(ko)
        graph_links, unresolved = self._link_entities(
            raw.user_id,
            ko.id,
            raw.id,
            enrichment.entities,
        )
        relation_candidates: list[dict[str, Any]] = []
        conflict_candidates: list[dict[str, Any]] = []
        if self.knowledge_graph:
            self._record_event_times(raw.user_id, content, graph_links)
            # Graph evolution remains review-only: explicit local phrases can
            # propose a relation, and incompatible claims can propose a
            # conflict, but neither path mutates established knowledge.
            relation_candidates = self.knowledge_graph.suggest_relations_for_knowledge(
                raw.user_id,
                ko.id,
            )
            conflict_candidates = self.knowledge_graph.detect_conflicts_for_knowledge(
                raw.user_id,
                ko.id,
            )
        auto_classified = bool(
            not force_pending
            and assessment.promotion_score >= 0.86
            and enrichment.quality_score >= 0.62
            and not unresolved
            and not relation_candidates
            and not conflict_candidates
            and not any(link.get("status") == "suggested" for link in graph_links)
        )
        suggestions = enrichment.to_suggestions()
        suggestions["graph_links"] = graph_links
        suggestions["unresolved_entities"] = unresolved
        suggestions["relation_candidates"] = relation_candidates
        suggestions["conflict_candidates"] = conflict_candidates
        inbox = InboxItem(
            id=new_id("inbox"),
            user_id=raw.user_id,
            raw_object_id=raw.id,
            knowledge_object_id=ko.id,
            status=InboxStatus.CLASSIFIED if auto_classified else InboxStatus.PENDING,
            suggested_tags_json=enrichment.tags,
            suggestions_json=suggestions,
            suggested_action="none" if auto_classified else "review_links",
            promotion_score=assessment.promotion_score,
            quality_score=enrichment.quality_score,
            classification_notes=(
                f"promoted; category={assessment.category}; promotion={assessment.promotion_score:.2f}; "
                f"quality={enrichment.quality_score:.2f}; graph_links={len(graph_links)}; "
                f"unresolved_entities={len(unresolved)}"
            ),
        )
        self.storage.store_inbox_item(inbox)
        return {
            "auto_classified": auto_classified,
            "inbox_id": inbox.id,
            "knowledge_object": self.storage.get_knowledge_object(ko.id, raw.user_id),
            "extracted_entities": enrichment.entities,
            "graph_links": graph_links,
            "unresolved_entity_suggestions": unresolved,
            "relation_candidates": relation_candidates,
            "conflict_candidates": conflict_candidates,
            "extracted_tags": enrichment.tags,
        }

    def _record_event_times(self, user_id: str, content: str, graph_links: list[dict[str, Any]]) -> None:
        """Best-effort temporal anchor for a freshly linked event entity.

        Only when the note links exactly one event is a detected date associated —
        with several events in one note it is ambiguous which the date belongs to,
        so those are left for the user to set explicitly.
        """
        if not self.knowledge_graph:
            return
        event_links = [
            link
            for link in graph_links
            if str(link.get("entity_type")) == EntityType.EVENT.value and link.get("entity_id")
        ]
        if len(event_links) != 1:
            return
        try:
            self.knowledge_graph.record_event_time_from_text(
                user_id, str(event_links[0]["entity_id"]), content
            )
        except Exception:
            LOGGER.debug("event time extraction failed", exc_info=True)

    def _link_entities(
        self,
        user_id: str,
        ko_id: str,
        raw_id: str,
        entity_candidates: list[dict[str, Any]],
    ) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
        graph_links: list[dict[str, Any]] = []
        unresolved: list[dict[str, Any]] = []
        if not self.knowledge_graph:
            return graph_links, list(entity_candidates)

        for candidate in entity_candidates:
            confidence = _clamp(float(candidate.get("confidence", 0.0)))
            entity = None
            if candidate.get("entity_id"):
                entity = self.knowledge_graph.get_entity(str(candidate["entity_id"]), user_id)
            if not entity:
                entity = self.knowledge_graph.find_entity(user_id, str(candidate.get("name") or ""))

            created = False
            method = str(candidate.get("method") or "unknown")
            explicit = method in DECLARED_ENTITY_METHODS
            # Creating a graph node is less destructive than merging, but we still require a
            # reasonably strong mention.  Weak names remain Inbox suggestions.
            if not entity and confidence >= (0.8 if explicit else 0.88):
                try:
                    entity = self.knowledge_graph.create_entity(
                        user_id,
                        str(candidate["name"]),
                        EntityType(str(candidate.get("entity_type") or EntityType.OTHER.value)),
                        metadata={
                            "created_by": "ingestion",
                            "extraction_method": method,
                            "source_raw_object_id": raw_id,
                            "initial_confidence": confidence,
                            "initial_mention": {
                                key: candidate[key]
                                for key in ("matched_as", "version", "evidence")
                                if candidate.get(key)
                            },
                        },
                    )
                    created = True
                except (ValueError, KeyError):
                    entity = None

            if not entity:
                unresolved.append(candidate)
                continue

            accepted = confidence >= 0.88 and (
                explicit or method in {"existing_entity_exact_mention", "explicit_identifier"}
            )
            status = "accepted" if accepted else "suggested"
            link = self.knowledge_graph.link_knowledge_to_entity(
                ko_id,
                entity["id"],
                user_id,
                confidence=confidence,
                evidence={
                    "method": method,
                    "raw_object_id": raw_id,
                    "matched_as": candidate.get("matched_as", candidate.get("name")),
                    "version": candidate.get("version"),
                    "extraction_evidence": candidate.get("evidence"),
                },
                status=status,
            )
            graph_links.append(
                {
                    "id": link.get("id"),
                    "entity_id": entity["id"],
                    "entity_name": entity.get("name"),
                    "entity_type": entity.get("entity_type"),
                    "status": status,
                    "confidence": confidence,
                    "created": created,
                }
            )
        return graph_links, unresolved
